### ISSUE TITLE
FindBar Tweak shouldn't highlight text based on selections made in user-editable fields

### ISSUE THREAD

**Issue by ronjouch** [Quicksaver/FindBar-Tweak#106]
(followup to a behavior first revealed in #102)

**Problem**: I use the `Tweaks → When Selecting Text → Fill the Findbar with the selected text` option of so that your addon behaves like HighlightAll (or any code editor). It works fine and correctly highlights instances of what's selected.

However, and contrarily to HighlightAll, it also highlights selections made in user-editable fields (like `<input>` and `<text>`), which feels weird because it ends up highlighting words (or part of words) that I transiently select as part of the editing process and not because I actually want to highlight them.

A video being worth a thousands pictures being worth a thousand words, [this screencast (webm, 1MiB)](https://dl.dropboxusercontent.com/u/368761/bugreport/findbar-tweak-highlighting-instances-of-keyboard-selection.webm) should be a million times more convincing than anything I can write.

**Proposed solution**: maybe FindBar Tweak could default to not highlighting anything based on text typed by the user in any kind of modifiable field.
→ What do you think of an additional `'... but not when inputting text inside entry fields'` sub-option that would be checked by default and be placed below `Tweaks → When Selecting Text → Fill the Findbar with the selected text`?
And it's the first idea that comes to mind, but maybe you have better ways to solve this glitch?

Thank you for your addon!

**Comment by DavidGP** [comment]
>> Anyway, I hope that one of the next versions will make it possible to have automatic highlighting on the page, while at the same time not doing anything to, you know, text boxes :)

>> What's more, I also look forward very much to multi-highlighting at some stage, as already discussed previously here:
#76 (comment)

> Both of those will definitely be on the next version

???

**Comment by Quicksaver** [comment]
@DavidGP who wrote in #125:
> Unfortunately, after one and a half years and now even in the completely rewritten extension, the problem is still present.
> :(

I'm replying to you here because there's no point in keeping two issues to track the same thing.

Unfortunately I was overly optimistic about many features before. You can obviously tell that there is so much that I had wanted to include but it has been next to impossible to do most of it yet. I'm very sorry about not being able to keep my word about this so far. :(

An option to not use selected text from input fields in the sidebar is on my shortlist of things to do, although I have no release date to give you. I'll try to squeeze it in for the next release, although no promises there. Highlighting multiple words in different colors will definitely take longer though.

**Comment by DavidGP** [comment]
OK thanks -- looking forward especially to the "not use selected text from input fields" feature.

**Comment by Quicksaver** [comment]
Well that was so easy now that I'm kind of ashamed I didn't do it sooner. :|

Care to give beta version 2.1b2 a try? https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1b2

**Comment by Quicksaver** [comment]
I forgot to mention, there's the option to re-enable the previous (current) behavior in the Tweaks pane in the add-on preferences.

**Comment by DavidGP** [comment]
Perfect! Thank you!

**Comment by Quicksaver** [comment]
Great! Let me know if you run into any trouble with it. I'm sorry again about the big delay in implementing this.

**Comment by DavidGP** [comment]
Oops, the "(don't) fill with text selected in editable elements" option seems to be defunct in Gmail. As soon as I select anything when editing a mail draft, it selects the same on the entire page :(

**Comment by Quicksaver** [comment]
Good catch! This will be fixed in the next release.

**Comment by DavidGP** [comment]
thanks!

**Comment by DavidGP** [comment]
I'm still seing this problem in Gmail! :(

**Comment by Quicksaver** [comment]
Hmm, maybe they changed something recently. I'll take a look.

**Comment by Quicksaver** [comment]
I think the new reply form they have. It seems to select everything in the reply textbox when you click outside of it... Which is just weird behavior on their part but whatever, let me try to figure out a way to prevent this.

**Comment by Quicksaver** [comment]
Hmm, it's not that gmail itself is selecting the contents of the reply box, it's that it's extremely easy (too easy) to select everything when you click outside of it.

For instance, if you place the cursor in the reply box and type in anything, then click outside with the mouse absolutely stopped, then it shouldn't select any text in the reply box as expected. But if you click outside while the mouse is moving, then it will "think" you dragged the mouse to select the actual textbox in the reply box (which also selects its contents of course).

Still bad behavior on their part, but can you confirm this is what seems to happen for you too? A fix for this will be far too specific, and if this is not your case then there's no point in even bothering and I should try something else.

**Comment by Quicksaver** [comment]
Turns out I was able to find a more general fix that doesn't rely on gmail keeping its current exact page structure indefinitely. Can you try [beta version 2.1.9b2](https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.9b2) and see if it fixes the issue for you as well?

**Comment by DavidGP** [comment]
Works perfect so far -- thanks!

**Comment by Quicksaver** [comment]
I'm glad to hear it. Let me know if it happens again. :)
