### ISSUE TITLE
Find in All Tabs stopped working

### ISSUE THREAD

**Issue by bottleblue** [Quicksaver/FindBar-Tweak#113]
For some reason the Find in All Tabs option doesn't work anymore. The whole right side is a blue color. 
![11](https://f.cloud.github.com/assets/3678136/2063309/374b386a-8cb4-11e3-99a1-6fec16dc7b06.jpg)

I haven't installed any new addons. When I disable all my addons except for this one it still doesnt work. But when I deleted prefs.js that fixed it. What do you think could be causing it?

**Comment by jmsDev1** [comment]
Hi.  I seem to be having exactly the same problems - just about EVERYTHING bottleblue mentioned (workarounds, partial fixes with viewing source from the console error link to the source, etc.) is happening to me in conjunction iwth Find in All Tabs not working.  I am using v.2b1.

The error I'm seeing with the Find in All Tabs button selected and hitting "Update Results" is:
    TypeError: FITtabsGroups is null findInTabs.jsm:542:0

If I hit the filter button (the megaphone-looking icon), it doesn't do anything and the error in console is:
    TypeError: FITtabsGroups is null findInTabs.jsm:63:5

Any suggestions short of messsing around with my profile?  (I have a lot of extensions and don't have the time to re-install and reconfigure them and/or with a new profile).

Thanks.

**Comment by jmsDev1** [comment]
Is it possible this (Find in All Tabs) only works if we've actually visited the tab in this session?  Because I have session restore on along with Firefox's option not to load a tab until I actually visit (click on) it.  And I recently restarted Firefox.

**Comment by Quicksaver** [comment]
It obviously can only search tabs that are already loaded, otherwise it has nothing to search. But the unloaded tabs should still show up in the lists, which is a whole different problem. There's a lot not working lately in FBT that I need to look into. I'll let you know when I do.

**Comment by Quicksaver** [comment]
I can't reproduce this at all currently. Could you please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience the problem.
