### ISSUE TITLE
Graphics glitch.

### ISSUE THREAD

**Issue by streetwolf** [Quicksaver/FindBar-Tweak#114]
Hovering and Selecting causes graphic glitch.

<a href="http://imgur.com/tABuNw4"><img src="http://i.imgur.com/tABuNw4.png" title="Hosted by imgur.com" /></a>

**Comment by Quicksaver** [comment]
This should be fixed in the latest beta. Could you please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still see it.
