### ISSUE TITLE
display bug

### ISSUE THREAD

**Issue by karokarolinka** [Quicksaver/FindBar-Tweak#121]
Hi,
in minor pages with java/fla/html5 code when I install new version of FindBar Tweak there is problem with color display, for example look at youtube.com and click on cog icon for change resolution (quality) - fonts color are very light blue (instead of black). But when I click CTRL+F fonts return to their normal black color.
Now I am using FindBar 1.4.9 - in this version, problem doesn't exist.
PS. Sorry for my English.

![findbar_colors_problem](https://f.cloud.github.com/assets/6717291/2196682/c7e8b4a6-98b2-11e3-8fd7-7ecad504dc68.jpg)

**Comment by Quicksaver** [comment]
I can't reproduce this at all currently. Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience the problem.
