### ISSUE TITLE
InstantFox breaks FindBar Tweak searching

### ISSUE THREAD

**Issue by MadscientistCC** [Quicksaver/FindBar-Tweak#124]
Here's the repro:

1) On Firefox 28, install InstantFox + FindBar Tweak.

2) Type into the URL bar "g any keywords".

3) Once the page loads, try to search with Ctrl+F.

4) The search bar should appear, but nothing is highlighted when typing.

5) In-page-search stops working for the tab this happens in, no matter where you navigate.

Note: in-page-search works fine with either InstantFox or FindBar Tweak installed, just not both.

**Comment by Drugoy** [comment]
Finally! :dancers: 
yay, it works!
