### ISSUE TITLE
FR: Make ScrollUp/Down over findbar to work as "next/previous"

### ISSUE THREAD

**Issue by Drugoy** [Quicksaver/FindBar-Tweak#129]
That would be nice if you'd let users switch between next/previous found results on the page without clicking, but simply with a mouse scroll, in case the cursor hovers the findbar.

**Comment by yfdyh000** [comment]
A similar idea, Ctrl+Up/Down to works, based from https://bugzilla.mozilla.org/show_bug.cgi?id=1178088.
