### ISSUE TITLE
Double matches counter

### ISSUE THREAD

**Issue by kilara1988** [Quicksaver/FindBar-Tweak#132]
I'm not sure if it happened today,but i noticed it today with 2nd May Nightly.
It seems that i get 2 matches counters.
Tried the beta,but still the same.
![untitled](https://cloud.githubusercontent.com/assets/1025376/2870368/8ef50f26-d2c0-11e3-91f7-37f13f2c53b6.png)

**Comment by Quicksaver** [comment]
This should no longer happen in the latest beta. Please try beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience the problem.
