### ISSUE TITLE
Visual/Ergonomic enhancements to the FindBar

### ISSUE THREAD

**Issue by Quisquose** [Quicksaver/FindBar-Tweak#137]
My FindBar buttons keep jumping around from left to right depending on whether the matches counter is currently displaying info or not. It's quite jarring and distracting.

Could you please find a way to keep the icons still?

I guess it either means leaving sufficient space between the Findbar text box and the icons, or putting the match text _after_ the icons. 

#60 would also be a solution (assuming users could position elements as they like).

Thanks!

**Comment by Quicksaver** [comment]
> My FindBar buttons keep jumping around from left to right depending on whether the matches counter is currently displaying info or not.

Hasn't happened for a few Firefox versions now, so no longer valid.

> Specifically for the top right position I'd recommend changing the order of items: put match info to the left of toolbar, then the input field and then the buttons.

Done in #186, although not exactly as suggested.

> Text "Phrase not found" is not even needed to be shown: red background in text field is already a good indicator of that.

I'm not sure I will add an option to remove this, at least not this directly. It's still a valid way to show that there are no matches found, and it doesn't really interfere all that much. I still have it in my to-do list, but it's not very high up.

> Text "25 of 28 matches" can be shortened to just "25/28", which is ~11 chars more ergonomic.

I thought about this a bit lately, and I don't think it's really necessary, it wouldn't really save that much space anyway, and "x/y" can be a bit harder to read at first.
