### ISSUE TITLE
Graphics glitch in v2b1.

### ISSUE THREAD

**Issue by streetwolf** [Quicksaver/FindBar-Tweak#140]
![fbt2b1](https://cloud.githubusercontent.com/assets/410799/3033163/c4aa51d2-e060-11e3-863a-281f78d92594.PNG)

Notice within the blue circles some extraneous pixels by the top curves.  You will have to blow the picture up especially to see the extra pixels on the left side.

I used a new profile btw.

**Comment by Quicksaver** [comment]
This should be fixed now as well. Please try the latest beta version 2b2 and reopen the issue if you still see the it.
