### ISSUE TITLE
Top right toolbar positioning bug: [pdf.js and other extra toolbars compatibility]

### ISSUE THREAD

**Issue by Drugoy** [Quicksaver/FindBar-Tweak#142]
1. There's a built-in pdf-viewer in Fx: pdf.js
it has it's own toolbar and I see that your add-on has an awesome integration with that util if toolbar is selected to be shown on top right:
<img src="https://i.imgur.com/LgUc6cw.png">

It even gets colored as dark as pdf.js's top toolbar is.

But, there's a positioning bug when firefox draws some toolbars over content-area of the window. On the screenshot above pdf.js control buttons are on their toolbar in content-area.
Now here's a positioning bug:
1. open 2 tabs: one normal and the other with some pdf viewed in pdf.js
2. set in findbar tweak options to not close findbar when switching tabs ("findbar starts closed in new tabs").
3. open tab 1 (normal) and open findbar there
4. switch to tab 2 and get this:
<img src="https://i.imgur.com/e9H0duC.png">
5. play a bit more with opening findbar and switching tabs and get this:
<img src="https://i.imgur.com/V3cdRNB.png">

**Comment by Quicksaver** [comment]
This should be fixed. Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience the problem.
