### ISSUE TITLE
[The fox, only better] add-on compatibility: positioning bug

### ISSUE THREAD

**Issue by Drugoy** [Quicksaver/FindBar-Tweak#143]
This issue is very similar to issue #142, but is related to compatibility with a quite popular <a href="https://addons.mozilla.org/en-US/firefox/addon/the-fox-only-better/">The fox, only better</a> add-on..
That add-on hides the nav-bar until user hovers any top toolbars and then the nav-bar re-appears.
The thing is that it gets drawn above content-area (over the page).
Thus, when that add-on is installed and nav-bar is shown - it fully overlays findbar, so findbar gets hidden behind nav-bar.

**Comment by Nidre** [comment]
Any expected date for this change? It's kind of annoying to see it overlayed by The Fox.

**Comment by Quicksaver** [comment]
No, sorry. I haven't forgotten about it, I just haven't come up with a good way to do it yet.
