### ISSUE TITLE
Pink marks on scrollbar sometimes don't get shown or get hidden after <next>/<prev> navigation

### ISSUE THREAD

**Issue by Drugoy** [Quicksaver/FindBar-Tweak#147]
The issue is better be tested on large pdf files opened in pdf.js, because searching there takes quite much time and this affects the subj issue.

**Comment by Quicksaver** [comment]
This should be fixed. Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience the problem.
