### ISSUE TITLE
Find in tabs: can't switch to entry with the same position on another tab

### ISSUE THREAD

**Issue by Infocatcher** [Quicksaver/FindBar-Tweak#148]
Example: open two tabs with https://github.com/Quicksaver/FindBar-Tweak/
Type "Find Toolbar" in find field (only one found entry for now).
Then try to switch between found entries (select tab in left list, then select entry in right list): clicks on entry in right list doesn't work.

Also the same for any other strings, e.g. for "Find" (7 matches for now): click on N'th row in right list works only once per tab.

**Comment by Quicksaver** [comment]
This should be fixed. Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience the problem.

**Comment by Infocatcher** [comment]
Thanks, looks fixed for me.

P.S. Extending of a find bar to search through tabs was more useful, like find bar vs find dialog/window: first one never overlaps content.
Anyway, thanks for update. And thanks for you work on that useful extension. :)

**Comment by Quicksaver** [comment]
The removal of the Find in Tabs lists embedded in the browser window is only temporary. I plan on writing a more intuitive replacement. Stay tuned! ;)

**Comment by Infocatcher** [comment]
Oh, great! Thanks in advance.
