### ISSUE TITLE
Prev/Next clears findbar

### ISSUE THREAD

**Issue by shenmaster** [Quicksaver/FindBar-Tweak#150]
When using the "Fill the Findbar with the selected text when opening it" the next/prev button will clear the Findbar and doesn't move to the next/prev match. This happens in the latest and dev version.

**Comment by Quicksaver** [comment]
This should be fixed. Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience the problem.

**Comment by gointern** [comment]
Seems to be working with 2b2 installed.

**Comment by mzso** [comment]
Works for me too.
