### ISSUE TITLE
can not identify the count number in dark color theme

### ISSUE THREAD

**Issue by alanwonder** [Quicksaver/FindBar-Tweak#152]
ver 30.0
see image
![feedback](https://cloud.githubusercontent.com/assets/3063644/3637177/b2c2b4ec-0ff8-11e4-84d5-6801ec20180e.png)

**Comment by Quicksaver** [comment]
I've made some improvements that should help with these situations. Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and let me know if you still run into any trouble about this.
