### ISSUE TITLE
Cursor position jumps to begining while typing in find box

### ISSUE THREAD

**Issue by MDominik13** [Quicksaver/FindBar-Tweak#158]
This is the same as a previously reported issue: https://github.com/Quicksaver/FindBar-Tweak/issues/115

When I start typing in the find box, I only get a few letters in before the cursor jumps to the beginning. This doesn't happen all the time but is very annoying when it does happen. 

Let me know if you need me to provide you with any of my information (other extensions, settings, etc).

**Comment by Quicksaver** [comment]
I can't reproduce this at all currently. Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience the problem.
