### ISSUE TITLE
Search term disappears (Win7&8.1)

### ISSUE THREAD

**Issue by Hikkup** [Quicksaver/FindBar-Tweak#160]
Sorry to be a nuisance as I'm pretty sure this is an ID10T error but the search term in the QuickFind window disappears when I change to any tab other than the one in which I entered the term and click the "next occurrence" arrow.  It's happening in both Win7 and Win8.1.  The QuickFind is v1.4.18 and the FF is 32.0.3.  It happens whether or not I have 'Find in all Windows' selected.  I run a butt-load of add-ons but InstantFox is not one of them.

Frankly, I'm a bit bewildered by all the options and settings.  My primary interest is that the QuickFind window remains open ALWAYS and that the search term does not change (or disappear) unless I change it deliberately.

**Comment by Quicksaver** [comment]
I can't reproduce this at all currently. Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience the problem.
