### ISSUE TITLE
Under FF32 very slow when moved to top

### ISSUE THREAD

**Issue by solf** [Quicksaver/FindBar-Tweak#163]
It was fine under FF24, but now that I've migrated to FF32 I've noticed that moving findbar to top makes it very slow -- slow to open and slow to type in (and it seems to max out single CPU too).

**Comment by Quicksaver** [comment]
I can't reproduce this at all currently. Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience the problem.
