### ISSUE TITLE
FBT doesn't work with e10s.

### ISSUE THREAD

**Issue by streetwolf** [Quicksaver/FindBar-Tweak#164]
FBT does not work with e10s enabled in Firefox.  Nightly will be turning e10s on as the default in the next week or two.  Any plans on getting an e10s version of FBT soon?

**Comment by mzso** [comment]
Just tried it. Too bad that even things not added by FBT are broken such as highlighting all  results.

**Comment by Quicksaver** [comment]
I'm actually working on it as we speak and it's looking pretty good so far in e10s. I hope to release the next beta still this month. :)

**Comment by mzso** [comment]
Cool.

**Comment by Quicksaver** [comment]
After a long wait, FBT is finally compatible with e10s! Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and let me know if you run into any issues.
