### ISSUE TITLE
malfunction with firefox 35 default pdf reader

### ISSUE THREAD

**Issue by jayashansaff** [Quicksaver/FindBar-Tweak#171]
Scroll-bar Highlighter don't work in pdf (Firefox 35 default PDF reader)
word counter of searched words don't work in pdf (Firefox 35 default PDF reader)

**Comment by Quicksaver** [comment]
There's a lot not working in pdfs. I'm still working on the new version. I'll let you know here when I release something that might fix it.

**Comment by jayashansaff** [comment]
ok ...thanks

**Comment by jayashansaff** [comment]
in addition, word highlight color in PDF is become very light.......and cant Change  it.
![untitled](https://cloud.githubusercontent.com/assets/10693311/5891379/295814b8-a4b8-11e4-9caa-1fa64b7ead6e.png)

**Comment by Quicksaver** [comment]
This should be fixed. Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience the problem.
