### ISSUE TITLE
'searched words highlight colour' become very light in firefox 35 default pdf reader

### ISSUE THREAD

**Issue by jayashansaff** [Quicksaver/FindBar-Tweak#172]
'searched words highlight colour' become very light in firefox 35 default pdf reader,, when using findbar tweak addone

but it working perfect in other web pages ..i mean html pages

**Comment by ggcroma** [comment]
I confirm highlighting in pdf docs is almost invisible. Furthermore subsequent finds miss the enhanced highlighting of a different color and circling.

**Comment by Quicksaver** [comment]
This should be fixed now. Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience the problem.
