### ISSUE TITLE
Responsive WIdth

### ISSUE THREAD

**Issue by X-Raym** [Quicksaver/FindBar-Tweak#178]
Hi!

It seems that the input search field doesn't have a responsive width. It staty the same no matter the Firefox window size, making some part of the UI not avaible if hidden.
Could it be corrected ?

Thanks for listening! :)

**Comment by Quicksaver** [comment]
I can't reproduce this at all currently. Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience the problem.
