### ISSUE TITLE
Sights tab... 

### ISSUE THREAD

**Issue by bandaid** [Quicksaver/FindBar-Tweak#181]
How do I change the ugly "pink" and annoying highlighting? 
Selecting the "pink" box does nothing.

If I navigate to the Highlights tab, I can change the "Highlights Color," but NOT within "sights" ....

**Comment by Quicksaver** [comment]
Did you uncheck the "Use same color as..." options above the color selector box?

**Comment by bandaid** [comment]
Thanks. The context wasn't very intuitive.

**Comment by Quicksaver** [comment]
I'm already planning a few changes to the preferences dialog to hopefully prevent other mix-ups like this.

**Comment by bandaid** [comment]
Actually, I just tried it again with what you suggested and the findbar continues to highlight active search text with "pink" highlighting.

**Comment by Quicksaver** [comment]
Hmm that's very strange, if you can use the color picker for the highlights, you should be able to use it for the sights as well (as long as both "Use same color as..." preferences above it are disabled of course).
