### ISSUE TITLE
RegEx Find compatibility

### ISSUE THREAD

**Issue by meoso** [Quicksaver/FindBar-Tweak#182]
I've installed [RegEx Find](https://addons.mozilla.org/en-US/firefox/addon/regex-find/) which works by itself; however, not with FindBar Tweaks enabled.  Also, if made to work together, it will need an icon for `Show button icons instead of labels`.  Thank you kindly.

**Comment by Quicksaver** [comment]
I highly doubt I will be adding compatibility for that add-on, since I'm planning to add RegEx find to FBT itself: #56.
