### ISSUE TITLE
FindBar-Tweak does not get focus when starting search

### ISSUE THREAD

**Issue by qpathname** [Quicksaver/FindBar-Tweak#183]
The new version (FindBar Tweak 2b2, Firefox 37.0.2 on Mac OS X 10.10.3) does not get input focus when you Command-f to start a search.  Command-f does open up the find bar, but I have to move the mouse to the find bar input window and click to set the focus to the bar.  This started immediately after the update.

**Comment by Quicksaver** [comment]
This could be a bug specific to Mac OS X, I'll have to check there to make sure. In the meantime, can you please tell me if the same happens when you disable all your add-ons except for FBT?

**Comment by qpathname** [comment]
It still happens with all other add-ons disabled.

Also, someone else seems to have the same issue:

https://addons.mozilla.org/en-Us/firefox/addon/findbar-tweak/reviews/705576/

**Comment by Quicksaver** [comment]
Yep, which is why I said this could be a Mac OS X specific thing. I'll try to check it out until the weekend at least, I hope, and I'll let you know.

**Comment by Quicksaver** [comment]
Ah I see what's happening. Good news is this should be fixed automatically when firefox 38 is released next week (tuesday I think). Since it's just around the corner, I don't think there's any need to fix it in the add-on. Please let me know if the issue persists after the update.
