### ISSUE TITLE
Scrollbar highlights appear over fullscreen html5 video

### ISSUE THREAD

**Issue by mzso** [Quicksaver/FindBar-Tweak#184]
Hello!
After I search for something on a youtube video page start watching the video the colored highlights which indicated a result's position on the scrollbar persist even when I go to fullscreen and the scrollbar isn't there anymore.
Rather bothersome to have tem on the right side of the video when I'm watching something.

Happens with both 2.0 beta and 1.x branch.

**Comment by Quicksaver** [comment]
Thanks for letting me know! This will be fixed in the next version.
