### ISSUE TITLE
FindBar frequently changes width when positioned top/right

### ISSUE THREAD

**Issue by BillHoag** [Quicksaver/FindBar-Tweak#186]
FindBar has a jittery appearance/width when it updates match counts and messages. A fixed width would be better on the eyes counts/messages are updated.

**Comment by Quicksaver** [comment]
I'm guessing you mean when it's on top?

**Comment by BillHoag** [comment]
Yes - I should have clarified this is when positioned top/right. Another solution besides fixed width would be to put the varying parts of UI to the left of the search text similar to the display of bottom/right.
