### ISSUE TITLE
Link-only quick search is borked on 2b2

### ISSUE THREAD

**Issue by mzso** [Quicksaver/FindBar-Tweak#187]
Hello!
Though apparently the search itself works the highlights and the counter doesn't.
All results are highlighted instead of only the links.

This doesn't work too smoothly on 1.4.18 either. When I close and then switch to the other quick find the highlights often don't change until I press ctrl+g several times or get stuck completely. (I'm not changing the search term)

**Comment by Quicksaver** [comment]
Thanks for letting me know! This will be fixed in the next version.

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2015. jún. 14. 12:17 CEST](https://github.com/Quicksaver/FindBar-Tweak/issues/187#issuecomment-111809655 "2015-06-14T10:17:59Z - Replied by Github Comment Enhancer"):
> Thanks for letting me know! This will be fixed in the next version.

Cool. When is it due?

**Comment by Quicksaver** [comment]
Hopefully in the next few weeks. Just need to finish a few other things.

**Comment by mzso** [comment]
Meanwhile I tried the updated files from master. When I change from link-only to normal quick findbar the highlights/counters are not updated. I press hotkey for normal quickfindbar > type the characters > wait for the findbar to auto-close > press hotkey for link-only > the highlights/counter stays the same. The results properly jumps to links though.
It seems to work in the opposite direction (link-to to normal).
One more smallish issue with this. It not enough opening the quick findbar for the highlights to appear or get updated, but you have to press ctrl+g. With normal (non-quick) findbar the highlights appear instantly.

**Comment by Quicksaver** [comment]
You're right of course, I hadn't considered that scenario. Could you please give beta version 2b3 a try (https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2b3) and see if switching into and out of links only mode clears the highlights for you?

**Comment by mzso** [comment]
It's much better now. When I open any quick findbar the old highlights are erased. Although I still have to press ctrl+g for the appropriate ones to appear. Ideally I wouldn't have to do that.

**Comment by Quicksaver** [comment]
Hmm the highlights are appearing for me after I type, without needing to do anything else. Please remember that if you're inputting find terms shorter than x characters (default is 3), the highlights appear only after a delay. Are you sure this is not what's happening?

**Comment by mzso** [comment]
I mean just opening the findbar with hotkey (eg:  "/") and not typing text.
There's a feature to open the quickfindbar by simply typing but I don't use that. It has issues.

**Comment by Quicksaver** [comment]
I figured you were using the hotkey, although it shouldn't really matter as it's the quick find bar all the same. Of course that if you don't type anything then there's nothing to highlight. I must be missing something...

> I still have to press ctrl+g for the appropriate ones to appear

What exactly did you mean with that? Can you please give me the exact steps you're doing until something goes wrong?

**Comment by mzso** [comment]
Well. The findbar remembers the previous search term. Which is loaded when I open it.
This is how I was testing. By keeping the search term, closing then switching between the two quick findbars.

**Comment by Quicksaver** [comment]
That's weird, when I open the findbar through the hotkeys ("/" for quick, " ' " for links) it is always cleared, and it should be cleared as it doesn't make sense to have a previous find term when using either of those modes.

That's why I was so confused, the find term should not be remembered when you switch between the two modes. Can you please try disabling FBT and see if when you toggle between the two modes the find term is still remembered? At least then I'll know it's really the add-on doing it or something else.

**Comment by mzso** [comment]
I like that it's remembered, as far as I remember it did ever since I use quickfind. I was sure it was a normal findbar or a FBT feature.
To me it load the previous search term all selected, much like the urlbar.

It's inconsistent. With the default "num /" shortcut it doens't always happen.
I also have two custom shortcuts because stupidly in firefox it's hardcoded to characters that I don't have on my localized keyboard. So I have this: gFindBar.startFind(gFindBar.FIND_TYPEAHEAD);
and this:
gFindBar.startFind(gFindBar.FIND_LINKS);

mapped to two keys with keyconfig.(.-)

If I use these the search term seems to always persist.

**Comment by Quicksaver** [comment]
Ah ok, now it makes sense. With those commands you're bypassing the whole routine where it checks whether or not it should clear the findbar. But since you prefer to keep the previous text, that works in your favor.

I made a quick change to accommodate for your case. Can you try beta version 2b4 (https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2b4) and see if the highlights are automatically applied when switching between links only and the quick find bar?

**Comment by mzso** [comment]
It seems to work perfectly now. Thanks.

**Comment by Quicksaver** [comment]
No problem, let me know if you have any other problems.

**Comment by mzso** [comment]
One last thought: Not clearing the quickbars could be a feature of FBT so they wouldn't get cleared with built in hotkeys either. (I myself use "num /" for numbers occasionally) Maybe people other then me would prefer it this way.

**Comment by Quicksaver** [comment]
Already in my to-do list. ;)

**Comment by mzso** [comment]
Great! :)
