### ISSUE TITLE
"Fill the findbar with selected text" has a few issues

### ISSUE THREAD

**Issue by petacz** [Quicksaver/FindBar-Tweak#190]
Ctrl+F does not close search bar
Double clicking on page text does not open find bar
and probably some other things

**Comment by jerrychern** [comment]
Have exact same problem as petacz post.  Suddenly, the Find bar doesn't respond to highlighted or clicked-on words at all.  Tried uninstalling, restarting and everything else I could think of.  It's at least comforting to know that I'm not the only one having this problem - same versions of Firefox and Findbar Tweak as petacz.  I'll be patient for awhile, but then it's onward and upward.  Was a very good Add-on that I depended on.  I hope you fix it soon.

**Comment by Quicksaver** [comment]
Have you tried the latest beta version 2b2, available in the Development Channel section at the bottom of https://addons.mozilla.org/firefox/addon/findbar-tweak/?

**Comment by jerrychern** [comment]
Thanks.  That’s an option I may value if it doesn’t get corrected in due time.  Much appreciated. 
--------------------------------------------------------------------------------

**Comment by petacz** [comment]
As I reported in Issue #189 the Highlights grid doesn't work in the latest beta version b2b.
So I have to stay on Firefox 37 and version 1.4.18

**Comment by r2evans** [comment]
@Quicksaver, thanks for the beta, that fixed this bug for me. (I was seeing similar behavior, where once the find field lost focus, `Ctrl-F` did not bring it into focus nor highlight the text. My habit pattern when I'm done searching is a quick `Ctrl-F Escape` to remove the find block and all highlighted references. This did not work in 1.4.18, now it appears to be working in 2b2. For the record, Win81_64, FF-38.0.1.)

**Comment by Luvechyle** [comment]
So was this ever fixed? the beta did not work for me. ctrl-f does open and close Findbar Tweak however it closes the findbar when it loses focus even though that option is not selected in my options. Additional if i select text prior to pressing ctrl-f, when i select ctrl-f the selected text will appear in the findbar. windows 8, ff 38.0.1

**Comment by r2evans** [comment]
@Luvechyle, I've tried toggling the lose-focus option and it behaves as expected for me. I'm not a dev for this add-on, but perhaps do you have any other extensions that could be interfering? (Have you tried temporarily disabling all other extensions -- annoying, I know -- and see if its behavior changes?)

**Comment by Quicksaver** [comment]
> when i select ctrl-f the selected text will appear in the findbar

This is the expected default behavior (of firefox itself even), and you can disable that in FBT's preferences, by disabling "Fill the findbar with the selected text when opening it".

> it closes the findbar when it loses focus even though that option is not selected

That's not expected of course. Like r2evans asked, have you tried disabling all your other add-ons? Also, are you sure you're not always using the quick find bar by default (again, check your preferences)?

**Comment by Luvechyle** [comment]
@r2evans, Thanks for the feedback. I only have Skype to Call and Duplicate this Tab enabled, these was always enabled. Not sure why they would be an issue now...?

**Comment by Luvechyle** [comment]
@Quicksaver 

My full sentence reads, ''Additional if i select text prior to pressing ctrl-f, when i select ctrl-f the selected text will appear in the findbar'' Prior here is the operative word and what i mean is for the findbar to work I must select text prior to opening the findbar. After that with the findbar open, if i select new text, the new text does not populate in the findbar instead i end up with two highlighted words...and the findbar stil has information on the first highlighted word.

Now this all started after the update to ff ver. 38.0.1 so maybe the solution is to downgrade?

**Comment by Quicksaver** [comment]
That's very different from what you wrote before...

> if i select new text, the new text does not populate in the findbar instead i end up with two highlighted words

Do you mean through the preference "Fill the findbar with the selected text"? If yes then yeah, I can see there are some issues with it that I need to look over.

> even if i select update results, it dooes not populate the new words

Now this bit I didn't understand... What "update results"?

**Comment by Luvechyle** [comment]
![update results](https://cloud.githubusercontent.com/assets/5648180/7825023/1d0e88c2-03d6-11e5-8dba-c3852876f4d0.png)

Sorry about not being clear before, double clicking words are not working or triggering the launch of the findbar

**Comment by Quicksaver** [comment]
That button is only for the find in all tabs lists, it does nothing for actual page highlights. Please install the beta 2b2 that I mentioned in my first reply, as the latest release is full of bugs.

**Comment by Luvechyle** [comment]
Ok, so did what you suggest, originally I installed the version at the top of the page. Now i can select text and the findbar activates however the Find in all tabs button needed to be selected for the search to look in all pages. even with that option enabled in setting, it does not search in all tabs. When i select find in all tabs a new window pops up even though in the prior version it uses to extend the search findbar, now its opening a new window.

![find in all tabs](https://cloud.githubusercontent.com/assets/5648180/7837626/406be118-0456-11e5-90d3-086010fe092f.PNG)

**Comment by Quicksaver** [comment]
Yes, that's the default behavior for now. I took out the previous lists embedded in the browser window because I'm planning to write a better and easier to use implementation for it, I just haven't gotten around to do it yet.

**Comment by Luvechyle** [comment]
Thanks for the update, because i have a list of over 400 items to find in 4 different tabs, the solution for me is to downgrade firefox and reinstall the findbar tweak before the beta. Thanks for your time..

**Comment by Quicksaver** [comment]
So this thread has gotten a bit out of hand... I fixed some issues with text selection populating the find bar, so I hope that will fix most things. Expect an update in the next few weeks.
