### ISSUE TITLE
[2b2] window loses focus when you click in any place of a scrollbar

### ISSUE THREAD

**Issue by mon4github** [Quicksaver/FindBar-Tweak#191]
FireFox 35
![finbar](https://cloud.githubusercontent.com/assets/12459758/7652059/6e979522-fb10-11e4-9da8-4cb6d34e79ea.gif)

**Comment by mon4github** [comment]
FireFox 35

**Comment by Quicksaver** [comment]
Thanks for letting me know! This will be fixed in the next version.
