### ISSUE TITLE
Ctrl+enter doesn't work on mozilla central

### ISSUE THREAD

**Issue by mzso** [Quicksaver/FindBar-Tweak#194]
Hello!
When I use the quickfind bar, very often I use control enter to open the highlighted link in a new tab. Something made this broken on nightly since it only works now after the findbar is closed. It's probably not e10s because it happens after I disabled it.

Oh yeah, it doesn't happen when FBT is disabled.

**Comment by Quicksaver** [comment]
Sorry about that, that's my fault. Could you give beta version 2b5 a try (https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2b5) and confirm that it works correctly?

**Comment by mzso** [comment]
Now it opens in the current tab. It should open in a new tab.

**Comment by Quicksaver** [comment]
That's default firefox behavior, I even created a new profile without any add-ons to confirm. Ctrl+Enter when finding a link through links-only search opens that link in the same tab. Maybe you are using Tab Mix Plus with some option that got reversed somehow?

Still, you're right that it should open in a new tab, I'll take a look and see if there's something I can do to change that in the add-on.

**Comment by Quicksaver** [comment]
Ah wait, are you by any chance trying with e10s enabled?

**Comment by mzso** [comment]
You may be right, though I don't remember it working any other way. :)

**Comment by Quicksaver** [comment]
If I try in Nightly (e10s enabled), Ctrl+Enter opens in the current tab, but if I try in Firefox Beta (not e10s), Ctrl+Enter opens in a new tab.

I think it's a firefox bug, and I even found out where exactly, if you can confirm this, I'll file a bug so they can fix it.

**Comment by mzso** [comment]
@Quicksaver 

Well, with nightly I normally do.
I tried it also. And I can verify that without e10s it still works.

**Comment by mzso** [comment]
Well at least with FBT disabled. If it's enabled it's broken again.

**Comment by Quicksaver** [comment]
https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2b6 There you go. :)

That part of the code in the add-on is a copy of e10s code, so it had the same problem. I fixed it in the add-on and will file a bug in bugzilla so that they can fix it in firefox as well. That was a nice catch!

**Comment by Quicksaver** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1174886 in case you're interested.

**Comment by mzso** [comment]
Great! Thanks.
