### ISSUE TITLE
Ctrl+F doesn't re-focus to the find input field

### ISSUE THREAD

**Issue by peter-kehl** [Quicksaver/FindBar-Tweak#195]
By default in Firefox (38, but also older), first Ctrl+F shows the Find panel and puts the focus in the Find input field. That still works with FindBar-Tweak.

In Firefox without FindBar-Tweak, after you then click/move focus out of Find panel (but you still have focus in Firefox) and you press Ctrl+F again, it moves focus to Find input again. However, with FindBar-Tweak 1.4.18.1 it doesn't move focus to Find input again. That is annoying.

Thank you for FindBar-Tweak. Please consider fixing the above.

**Comment by Quicksaver** [comment]
This should already be fixed in the latest beta https://github.com/Quicksaver/FindBar-Tweak/releases. Please try it out and let me know if you still have issues.
