### ISSUE TITLE
Highlight grid not working inside iframe

### ISSUE THREAD

**Issue by deant** [Quicksaver/FindBar-Tweak#197]
I installed beta version 2b7 as suggested, but I still get the following problem:

In my iframe, the highlight grid doesn't work:  It either shows nothing at all, or else it highlights the iframe's entire scrollbar, as in this image:

![sample page](https://cloud.githubusercontent.com/assets/4946606/8287479/79c0aa86-1953-11e5-831c-c293c26aed6a.png)

As this is a private website (an administration back-end for a corporate gifts company), I can't give you a link to it.  But I can send you saved copy of the page, if you can tell me where to send it to!

**Comment by Quicksaver** [comment]
You're right that something appears to be wrong in there, you got me very curious as to what it can be, I wouldn't expect it to not show the grid in what is clearly a scrollable iframe (nothing like the example in the other topic). You can send it directly to my e-mail if you can at quicksaver@gmail.com

**Comment by deant** [comment]
Sent.

**Comment by Quicksaver** [comment]
Thanks, it did help a lot! In short, there were two problems; one was that the add-on did not account for iframes being used as the main content like that (the big mark you were seeing was the iframe itself], and the other was the webpage's own stylesheet was overriding some of the grid's styling, which was making the actual hits invisible (i.e. they would have been visible even behind that big mark in the screenshot).

I tried to fix both these issues, or at least everything seems to work for me now. Could you please try beta version v2b8 (https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2b8) and let me know how it works for you?

**Comment by deant** [comment]
That works now, thanks.

The only issue I experienced is that after upgrading to v2b8, it seemed to upgrade OK, but didn't actually work at all (no hits, when there should have been) until I restarted the browser.  Maybe that's just a beta thing, but if the release version does that without notifying that a browser restart is required, lots of people are going to report problems...

**Comment by Quicksaver** [comment]
Yep, thanks for letting me know! I had noticed it last night when I updated in my main profile, I already fixed it so it shouldn't happen on future updates.
