### ISSUE TITLE
Internal scrollbar highlighting

### ISSUE THREAD

**Issue by justanotheranonymoususer** [Quicksaver/FindBar-Tweak#199]
Page:
https://gitter.im/notepad-plus-plus/notepad-plus-plus

Screenshot (see red arrows):
![2015-06-27 01_09_34-notepad-plus-plus_notepad-plus-plus - gitter](https://cloud.githubusercontent.com/assets/5781692/8388354/b3379806-1c69-11e5-88ce-9c1278c43742.png)

Not sure that it's possible to fix, but that would be nice if it is.

**Comment by Quicksaver** [comment]
#89
