### ISSUE TITLE
Not working with developer edition

### ISSUE THREAD

**Issue by pihentagy** [Quicksaver/FindBar-Tweak#200]
With Firefox Developer Edition 40.0a2 (2015-06-29) it does not work. (no hightlights, no visual clues, when finding again, no highlighting in scrollbar)

**Comment by Quicksaver** [comment]
Are you using FBT version 2? (https://addons.mozilla.org/firefox/addon/findbar-tweak/versions/)

**Comment by pihentagy** [comment]
Great. Works as before (y)
