### ISSUE TITLE
Show quick findbar if findbar is hidden when Finding (Again) and there's no results

### ISSUE THREAD

**Issue by mzso** [Quicksaver/FindBar-Tweak#201]
Apparently ctrl+g-ing on a new tab though starts jumping between results. Only the green highlight appears the other results are not highlighted.

Also I think the (quick?)findbar should pop-up at least when there aren't any results, otherwise it's just confusing.

**Comment by Quicksaver** [comment]
> Apparently ctrl+g-ing on a new tab though starts jumping between results.

You need to enable the preference "Also highlight on Find Again (F3)" in the Highlights pane

> Also I think the (quick?)findbar should pop-up at least when there aren't any results, otherwise it's just confusing.

Indeed. I wanted to add this for version 2 but must have forgotten. Thanks for reminding me.

**Comment by Quicksaver** [comment]
This change is also in v2.0.1b5 BTW.

**Comment by mzso** [comment]
Great. Thanks.

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2015. júl. 5. 19:05 CEST](https://github.com/Quicksaver/FindBar-Tweak/issues/201#issuecomment-118638497 "2015-07-05T17:05:41Z - Replied by Github Comment Enhancer"):
> > Apparently ctrl+g-ing on a new tab though starts jumping between results.
> 
> You need to enable the preference "Also highlight on Find Again (F3)" in the Highlights pane

Okay, so I had it enabled. It doesn't work in this case.
When I switch to a new tab and press ctrl+g no highlights appear outside the selected one (green), not on page, neither on the scrollbar. The quickfindbar opening would also be nice, as when there's no result(which works fine).

**Comment by Quicksaver** [comment]
> When I switch to a new tab and press ctrl+g no highlights appear outside the selected one (green)

Indeed they don't, this is very serious, I don't know how I could have missed that...

> The quickfindbar opening would also be nice, as when there's no result

This I am also planning to add (just made sure it's on my to-do list, so I don't forget about it as well), but I want to add it as an option, and it requires a little bit more code as there are more cases to cover. They're different situations after all, when there are no matches it seems like nothing happens, so it makes sense to at least always show the quick findbar to show that "something" happened. While when there are matches at least it cycles through them so you already know that "something" did happen, so it's not as critical I believe.

**Comment by Quicksaver** [comment]
There we go. https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.0.1b6

**Comment by mzso** [comment]
Cool. It seems to work fine now.
