### ISSUE TITLE
Ctrl+F shortcut stops working after initial search

### ISSUE THREAD

**Issue by krandell** [Quicksaver/FindBar-Tweak#202]
As reported in the reviews, Ctrl+F does not reselect the search box in Firefox 38 and 39, possibly earlier ones too.
https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/reviews/
Developer appears to be aware of this but I thought I'd add a proper issue tracker for it.

**Comment by Quicksaver** [comment]
This should be already fixed in the latest version 2 (at the top of https://addons.mozilla.org/firefox/addon/findbar-tweak/versions/). Give it a try and let me know if you still have problems.
