### ISSUE TITLE
Add Chinese Traditional(zh-TW) language, pls.

### ISSUE THREAD

**Issue by LNDDYL** [Quicksaver/FindBar-Tweak#204]
thx!

BTW, I can translate it into Chinese Traditional.

https://github.com/Quicksaver/FindBar-Tweak/tree/master/chrome/locale

**Comment by Quicksaver** [comment]
I can't add the zh-TW yet because it is only barely half translated. You're welcome to contribute to it or any other localization though, please read the Readme at https://github.com/Quicksaver/FindBar-Tweak for the steps on how to do it.

**Comment by LNDDYL** [comment]
![_2015-07-25t10-21-35 220z](https://cloud.githubusercontent.com/assets/4318463/8889028/001f8236-32fa-11e5-94b3-92c2c12c627a.png)
Why? Why? Why?

**Comment by Quicksaver** [comment]
I don't know, are you sure you inserted valid information (e-mail, username, etc)?
