### ISSUE TITLE
Don't show sights on current match when selecting text

### ISSUE THREAD

**Issue by thenoncoder** [Quicksaver/FindBar-Tweak#205]
When I select any piece of text, the findbar automatically opens, even though I never wanted it to.
I looked at the options, and there does not seem to be any sort of option to disable that!

**Comment by Quicksaver** [comment]
Add-on preferences - Tweaks pane - "When Selecting Text" group - "Show the Quick Findbar when selected text is used" checkbox.

Is that what you were looking for?

**Comment by thenoncoder** [comment]
That was it! Thanks a lot bro! :)

**Comment by thenoncoder** [comment]
But, now, when I select any piece of text, the *focus location* circle thing still gets activated, what do I do about this? :)

**Comment by Quicksaver** [comment]
I was sure I had changed that behavior, I'll have to fix it as it's obviously useless to show sights where you just selected text. Thanks for letting me know.

**Comment by Quicksaver** [comment]
This will be fixed in the next version. If you'd like to try it now, you can try the latest beta version 2.0.1b9 at https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.0.1b9

**Comment by thenoncoder** [comment]
Have you got an xpi for that beta? Because I don't want to make it myself from the install.rdf and all of that :)

**Comment by Quicksaver** [comment]
It's in that page I linked. But I've already uploaded the final 2.0.1, so you're probably better off installing that instead, you can find it at the top of https://addons.mozilla.org/firefox/addon/findbar-tweak/versions/

**Comment by thenoncoder** [comment]
Still shows sights where I just selected text in the latest version!

**Comment by Quicksaver** [comment]
It's not for me. Are you sure you installed version 2.0.1 (it's not updated automatically to this version yet)? What operating system and firefox version are you using?

**Comment by thenoncoder** [comment]
I manually installed the extension again from AMO, and sights are still showing where I just selected text!

**Comment by Quicksaver** [comment]
Where from AMO? From the link I gave you? Also, OS and firefox version?

**Comment by Quicksaver** [comment]
Also, can you give beta version 2.0.2b1 a try please? https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.0.2b1

**Comment by thenoncoder** [comment]
Um, I installed it from the amo page [here](https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/)
I'm on Firefox 38.0.1 / Windows 8.1

**Comment by thenoncoder** [comment]
I'll try 2.o2b1 and see if things are fixed.

**Comment by Quicksaver** [comment]
That's version 2. Version 2.0.1 hasn't been reviewed yet by the AMO reviewers, so it won't appear in the front page yet. You have to go to the page I linked you to and install it directly.

**Comment by thenoncoder** [comment]
This issue is finally fixed in 2.02b1
