### ISSUE TITLE
Skin: FTDeepDark integration

### ISSUE THREAD

**Issue by GTMelo** [Quicksaver/FindBar-Tweak#210]
I've been using the [FTDeepDark theme](https://addons.mozilla.org/pt-br/firefox/addon/ft-deepdark/) for longer than I remember. Would be a nice tweak to have the findbar following the same style, or at least just the colors:

![000180 - 2015-07-30 09_42_32-findbar tweak __ complementos para o firefox](https://cloud.githubusercontent.com/assets/11579322/8983472/ec373e08-36a0-11e5-8a83-f56287809fd5.png)

I have no experience in firefox addon development, but I suppose this wouldn't be too dramatic to implement either. It would require a border-top (maybe not even that), background gradient (to rgb 35,35,35 -> 30,30,30 - I *think*) and matching text color. Plus a config in the settings to enable or disable the alternative style.

**Comment by Quicksaver** [comment]
Theme integration issues like these are better fixed from the theme itself. Please contact the theme developers first and see if they can add support for the add-on in the theme. Feel free to direct them to issue #22 which has very simple and easy-to-follow instructions on how to do this.

**Comment by Quicksaver** [comment]
Fixed by 6405d81caaea64f53ccc0f37fbb44871b9bdef2f.
