### ISSUE TITLE
Top search bar weird dots in corners

### ISSUE THREAD

**Issue by lightonflux** [Quicksaver/FindBar-Tweak#211]
![bildschirmfoto vom 2015-07-31 15 24 42](https://cloud.githubusercontent.com/assets/1377943/9008144/5328ab40-3798-11e5-90be-0947fd359098.png)

The are two white dots in the corners of the search bar, if is is displayed at the top. 

I use the dark theme, that was introduced which the firefox developer browser. 

Key: 
> browser.devedition.theme.enabled

**Comment by Quicksaver** [comment]
I thought I had fixed that already, I'll be sure to look into it again. Thanks for letting me know!

**Comment by Quicksaver** [comment]
I obviously hadn't fixed it already like I thought. This will be fixed in version 2.0.2.
