### ISSUE TITLE
Addon cannot be verified

### ISSUE THREAD

**Issue by pihentagy** [Quicksaver/FindBar-Tweak#212]
Using firefox developer edition, it complains about unverified addon, and links to this:
https://support.mozilla.org/hu/kb/add-on-signing-in-firefox?redirectlocale=en-US&as=u&redirectslug=add-ons-signing-firefox&utm_source=inproduct

**Comment by Quicksaver** [comment]
What version of the add-on do you have installed? All versions should be signed already.

**Comment by pihentagy** [comment]
Sorry, it was some stupid transient issue with my browser
