### ISSUE TITLE
Conflict with Save Text to File add-on

### ISSUE THREAD

**Issue by cchris005** [Quicksaver/FindBar-Tweak#213]
Hi,
I happen to use both this very useful add-on and [Save Text to File](https://addons.mozilla.org/fr/firefox/addon/save-text-to-file/) (v2.6.9). When both are activated, and if I use STF's option to display the option dialog when saving text, then STF doesn't understand I selected any text. If this option is unchecked, or if FindBar is deactivated, everything is fine.
I first asked the author of STF, and he defers the bug to you. Hopefully this is not starting a ping-pong game...
Here is the description from STF's standpoint: https://addons.mozilla.org/addon/save-text-to-file/reviews/721362/ (second item).
Thanks for the useful extension!
CChris

**Comment by Quicksaver** [comment]
First of all, if you haven't already, can you update FBT to the latest release (v2) and see if that still happens?

**Comment by Quicksaver** [comment]
Actually, since you're already at it, might as well try version 2.0.2, in case it fixes the issue for some reason. You can find it at the top of https://addons.mozilla.org/firefox/addon/findbar-tweak/versions/.

**Comment by cchris005** [comment]
Hi, and thanks for the quick reply!

I'm stuck at work with FF31.1.1 ESR, and this v2.0.2 would not install here. Will try tonight at home on FF39 and keep you posted.

CChris
----- Mail d'origine -----
De: Luís Miguel <notifications@github.com>
À: Quicksaver/FindBar-Tweak <FindBar-Tweak@noreply.github.com>
Cc: cchris005 <oedoc@free.fr>
Envoyé: Tue, 11 Aug 2015 14:18:58 +0200 (CEST)
Objet: Re: [FindBar-Tweak] Conflict with Save Text to File add-on (#213)

Actually, since you're already at it, might as well try version 2.0.2, in case it fixes the issue for some reason. You can find it at the top of https://addons.mozilla.org/firefox/addon/findbar-tweak/versions/.

---

**Comment by Quicksaver** [comment]
Unfortunately the latest FBT version doesn't support anything older than Firefox 38, as the differences between Firefox versions have become too great for me to manage backwards compatibility like that. You might want to recommend to whomever is in charge at your workplace to update to the latest ESR 38.2, as 31.1.1 is very old even by ESR standards. But until then FBT 1.4.18 should work fine there at least. ;)

At home please update to Firefox 40 as well (it was released this week), since you're at it. It shouldn't make a difference, but who knows.

**Comment by cchris005** [comment]
Hi again,

At home, I'm still using FF39.0.3. FindBar Tweak 2 (25/07/2015) cohabits seamlessly with SaveTextToFile v2.7.0. v2.0.2 doesn't make a difference.
Since mine is a large organisation, I'll have to wait for a few more months till they upgrade everyone's machines. Obviously the problem at work is an old-versions-of-everything issue. Guess I just have to wait and skirt around the inconvenience meanwhile.
At any rate, thanks for taking care to investigate.
CChris

----- Mail d'origine -----
De: Luís Miguel <notifications@github.com>
À: Quicksaver/FindBar-Tweak <FindBar-Tweak@noreply.github.com>
Cc: cchris005 <oedoc@free.fr>
Envoyé: Fri, 14 Aug 2015 11:09:01 +0200 (CEST)
Objet: Re: [FindBar-Tweak] Conflict with Save Text to File add-on (#213)

Unfortunately the latest FBT version doesn't support anything older than Firefox 38, as the differences between Firefox versions have become too great for me to manage backwards compatibility like that. You might want to recommend to whomever is in charge at your workplace to update to the latest ESR 38.2, as 31.1.1 is very old even by ESR standards. But until then FBT 1.4.18 should work fine there at least. ;)

At home please update to Firefox 40 as well (it was released this week), since you're at it. It shouldn't make a difference, but who knows.

---

**Comment by Quicksaver** [comment]
Since FBT v2 works fine in FF39 for you, I'm closing this issue. I do understand the situation of having outdated software in those cases, but there's really nothing I can do about FF31 anymore, as I explained. I hope they update it soon. :)

Please let me know if you do run into any other issues.
