### ISSUE TITLE
FindBar placed on top upper right not looking correct

### ISSUE THREAD

**Issue by streetwolf** [Quicksaver/FindBar-Tweak#215]
Shouldn't it look like it does on the upper left?
http://imgur.com/7VCDOus

**Comment by Quicksaver** [comment]
I was just replying to your e-mail. :)

You're absolutely right, this is major, I don't know how I missed that. Thanks for letting me know. I'll try to fix it still today.

**Comment by streetwolf** [comment]
Always glad to help.


-----
Gary

----- Original Message -----

**Comment by streetwolf** [comment]
Any progress on this Luis?  If you need me to test a new version with the fix let me know.

**Comment by Quicksaver** [comment]
This should actually be very simple to fix. I just got caught up in another bug for TFOB that took me the whole morning to fix, and then didn't have enough time. I'll get to this tomorrow first thing probably, and I'll probably upload the fixed version immediately. Unless you find me any more bugs of course. :)
