### ISSUE TITLE
Search text showing as not found.

### ISSUE THREAD

**Issue by theaulddubliner** [Quicksaver/FindBar-Tweak#217]
Since the 2.0 update, when I open the findbar and type some known text I get 'phrase not found'. When I close and reopen the findbar it will then highlight the matches on the page but does not scroll. Grid and Sights are also not working for me.

I have little doubt this issue has more to do with the many extensions I have rather than a bug in this one.

Is there a log I can submit?

**Comment by Quicksaver** [comment]
It does sound like a conflict with another add-on. A log wouldn't be of much help until you can tell me which add-on is causing it.

First you should confirm that it really is a conflict, by disabling all your other add-ons and themes except for FBT, and see if searches run fine then (they should).

Then enable/disable your add-ons one or a bunch at a time, until you can narrow it down to the exact add-on that's causing it.

**Comment by Quicksaver** [comment]
I can't do anything without more information. :(
