### ISSUE TITLE
Unloaded tabs show "Nueva petaña" as title ('New tab')

### ISSUE THREAD

**Issue by Zheitk** [Quicksaver/FindBar-Tweak#218]
From the latest update (2.0.4), whenever I unload a tab (using UnloadTab), the tab title changes to "Nueva pestaña" (I'm on a Spanish system).
Deactivating this addon solves the problem.

**Comment by Quicksaver** [comment]
I've already fixed it but haven't uploaded the new version yet. Could you please give beta version 2.0.5b1 a try and let me know if you have any other issues with UnloadTab?

**Comment by Quicksaver** [comment]
Oops, here's the link: https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.0.5b1
