### ISSUE TITLE
[Not FBT] Current Hit Colour in pdf's overlaps text

### ISSUE THREAD

**Issue by FatOrangutan** [Quicksaver/FindBar-Tweak#219]
Expected behaviour / FF's default behaviour: The current highlight should be behind the text / leave the text visible:
![default](https://cloud.githubusercontent.com/assets/8336638/9568969/5657ada0-4f78-11e5-80cd-46f4d2c94270.PNG)
With FindBar Tweak 2.0.4: The highlight overlaps the text:
![bug](https://cloud.githubusercontent.com/assets/8336638/9568974/6225713a-4f78-11e5-8dc9-ca660260a3b8.PNG)

I experience that bug with all pdf's; the one I am using right now is this one: http://www.upsc.gov.in/directory/2012/web_dir2012_eng.pdf

**Comment by Quicksaver** [comment]
It appears fine for me. What Firefox version and operating system are you using? Also, does the same happen if you disable all your other add-ons and themes except for FBT?

**Comment by FatOrangutan** [comment]
On my configuration, I narrowed the problem to Textmarker (https://addons.mozilla.org/en-US/firefox/addon/textmarkerpro/): enabling it causes the above bug, disabling it fixes everything.
I am gonna try and inform the concerned developer.

**Comment by Quicksaver** [comment]
Hmm, I tried disabling FBT and I still see the issue when only Textmarker is enabled. Can you try to disable FBT and see if that also happens for you? If it does then there's really nothing I can do, as it's a problem with Textmarker itself and not really an incompatibility between the two add-ons.

(Just a heads up: I had an issue where FBT would fail to deinitialize when I tried to disable it with the PDF page still open, so you might have to restart the browser for FBT to fully disable. I'll look into that tomorrow.)

**Comment by FatOrangutan** [comment]
You are right. I began with a fresh profile and installed only Textmarker and could still observe the bug. FBT has nothing to do with this. Sorry for the confusion.
