### ISSUE TITLE
Unable to search for highlighted text

### ISSUE THREAD

**Issue by Luvechyle** [Quicksaver/FindBar-Tweak#222]
I am trying to search through a list of  names but when i highlight the name i want to find it does not prompt the findbar to open. however if i select the text then hit ctrl-F, the findbar will be triggered and populate the highlighted text. is this the intended method? In the past, under 'tweak' - 'when selecting text' all four options are checked off, and this will trigger the findbar once text is highlighted. Im using Mozilla FF  40.0.3, FBT version 1.4.18.1 - signed..

**Comment by Quicksaver** [comment]
Why are you using v1.4.18? Didn't yours update automatically to the most recent version? If it didn't, please update manually and try again.

**Comment by Luvechyle** [comment]
Updated now, only problem is find in all tabs is detached from the findbar but i believe someone already opened.
