### ISSUE TITLE
"Highlight all matches by default" causes flickering sometimes

### ISSUE THREAD

**Issue by justanotheranonymoususer** [Quicksaver/FindBar-Tweak#223]
With the latest version, when I select a word and press Ctrl+F, sometimes the highlighting flickers like crazy, as if it highlights the words in an infinite loop.

**Comment by Quicksaver** [comment]
I've never seen this happen to me. Can you try to find some exact steps to reproduce this? Also, does this happen when all your other add-ons are disabled?

**Comment by justanotheranonymoususer** [comment]
I might have found a reproduction case.
Open the following page:
http://stackoverflow.com/questions/528830/sql-sort-by-version-number-a-string-of-varying-length

Go to the second answer, select the "hierarchyid" word, and press Ctrl+F.

**Comment by Quicksaver** [comment]
Hmm indeed, I do see it, I have no idea what is happening though. I need to investigate. Thanks for reporting this!

**Comment by Quicksaver** [comment]
Ok I think I fixed it. Would you care to give beta version 2.1b1 a try? https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1b1

**Comment by justanotheranonymoususer** [comment]
Seems to be working correctly now, thanks!

**Comment by Quicksaver** [comment]
I'm glad to hear it, let me know if it happens again.
