### ISSUE TITLE
The number of items found should be updated on frames

### ISSUE THREAD

**Issue by sdavidg** [Quicksaver/FindBar-Tweak#226]
Download this file (https://www.dropbox.com/s/poew94qil95s276/bug.7z?dl=0) and open main.html.

1) Press ctrl+f
2) Type 1111 in search box and check "Highlight all"
3) The items found appear highlighted and the number of items found is shown
4) Click in "frame 222" -> The items found appear highlighted but the number of items found is not update
5) Click in "frame 111" -> The items found appear highlighted but the number of items found is not update

Fb 41.0.1
FindBar Tweak 2.1

**Comment by Quicksaver** [comment]
It's working fine for me. Could you try the latest version 2.1.1? (still in the queue, uploaded last night: https://addons.mozilla.org/firefox/addon/findbar-tweak/versions/)

**Comment by sdavidg** [comment]
Yes, works fine with 2.1.1
Thanks

**Comment by Quicksaver** [comment]
Glad to hear it. :)
