### ISSUE TITLE
[only idea] Not sensitive for punctuation

### ISSUE THREAD

**Issue by dimmuboy** [Quicksaver/FindBar-Tweak#227]
Is there any way to find text on site without punctuation sensitivity?
I mean that if I looking for "Vysoké Tatry" I can write only "Vysoke Tatry" for search them.

**Comment by Quicksaver** [comment]
#44 and [bug 202251](https://bugzilla.mozilla.org/show_bug.cgi?id=202251)

In short, it will be implemented in Firefox, or if they end up not doing it I will add it to the add-on, eventually. :)
