### ISSUE TITLE
Doesn't work anymore with latest FF nightly.

### ISSUE THREAD

**Issue by Betsy25** [Quicksaver/FindBar-Tweak#228]
Today, this patch was pushed into the nightlies, which renders FindBar Tweak non-working.
No longer highlights any matches, arrow & F3 keys also no longer do what they should.

https://bugzilla.mozilla.org/show_bug.cgi?id=1140512

**Comment by Quicksaver** [comment]
Please try this build which has a quick fix: https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.3a1

**Comment by streetwolf** [comment]
Your 'quick fix' appears to be working fine.  Also, the OSB problem didn't return with your fix as you expected.

**Comment by Quicksaver** [comment]
> the OSB problem didn't return with your fix as you expected

That's admittedly unexpected... But I'm not going to complaint about it, let's see if it holds like that. :)

**Comment by Betsy25** [comment]
Fine ! :+1:

**Comment by jg-github** [comment]
Thanks for the fast fix. It appears to work fine.

**Comment by Betsy25** [comment]
Don't know what the FF devs did now, but once again "Search when i start typing" ain't working anymore;

**Comment by Quicksaver** [comment]
That was me actually, [bug 1218351](https://bugzilla.mozilla.org/show_bug.cgi?id=1218351). :) I've already fixed it though, you can try [beta version 2.1.6b2](https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.6b2) if you want, although I should be releasing it sometime this weekend.

**Comment by Betsy25** [comment]
You're a quick saver, @Quicksaver :laughing:
