### ISSUE TITLE
When set the Findbar to be top right, the URL preview goes to the right too

### ISSUE THREAD

**Issue by NoXPhasma** [Quicksaver/FindBar-Tweak#229]
With the update to 2.1.2 the URL preview is shown always at the bottom right of the browser window, instead of bottom left.

To reproduce:
- Go to the Findbar Tweak settings.
- Set the Findbar to be on top of the browser and to be right.
- Hover any URL in Firefox.

Finbbar Tweak Version 2.1.2
Firefox Version: 41

**Comment by Quicksaver** [comment]
Thanks for letting me know, I'll be sure to look into it.

**Comment by hackel** [comment]
Confirmed on FF 43a2 as well.

**Comment by Speravir** [comment]
The view for different screen sizes (I don’t know the English term for this, some years ago it was [Responsive Design View](https://hacks.mozilla.org/2012/07/debugger-responsive-design-view-and-more-in-firefox-aurora-15/)), in Windows activated with CTRL+SHIFT+M, is also affected.
