### ISSUE TITLE
Findbar favorites

### ISSUE THREAD

**Issue by Speravir** [Quicksaver/FindBar-Tweak#230]
It would be fine, if you could at least add compatibility to the addon [Findbar Favorites](https://addons.mozilla.org/firefox/addon/findbar-favorites/), or – in my eyes better – enhance Findbar Tweaks to provide such a list of predefined search terms. Judging from the images the other addon is only usable with the mouse, something usable with the keyboard like a drop down list just like with the address or search bar of Firefox would be much better I think.

I found one in some kind similar request here, issue #83: [Search History](https://github.com/Quicksaver/FindBar-Tweak/issues/83). Perhaps a solution could combine both features.

**Comment by Quicksaver** [comment]
I believe the problem with FIndbar favorites is that it will hardly work anymore in the latest versions of Firefox, so there's no point in "adding compatibility" for it.

For what it's worth, I don't believe I will add this specific feature. However, in addition to #83, I also plan to add a feature similar to [Find Suggest](https://addons.mozilla.org/firefox/addon/prospector-find-suggest/) which I'm sure will be much more useful and powerful than Findbar Favorites.

**Comment by Speravir** [comment]
OK, nevertheless thanks for your (fast) reaction. And I’m looking forward to this planned enhancement. Yes, this seems to do the same job, I’m interested in. Also with what I suggested above one would have to start typing letters.
