### ISSUE TITLE
With "Place on the right" option, the status bar popup is moved to the right

### ISSUE THREAD

**Issue by abrowne** [Quicksaver/FindBar-Tweak#231]
If I choose the "Place on the right" option, Firefox's status bar popup (that shows the URL of a link on hover) is moved to the right. It doesn't happen until the findbar is activated for the first time, but then it persists when the findbar is closed.

Tested in OS X with Beta and Nightly and Linux (Fedora's build).

**Comment by Quicksaver** [comment]
#229 ;)

Will be fixed in the next version, I should upload it this week.

**Comment by abrowne** [comment]
Thanks for the (very!) quick answer. I did try searching, but I didn't use the same name for that popup... Just donated $5.

**Comment by Quicksaver** [comment]
Thank you very much, I really appreciate it! You are an awesome person. :)
