### ISSUE TITLE
Resizes Web Content

### ISSUE THREAD

**Issue by Nidre** [Quicksaver/FindBar-Tweak#233]
The content area in tab automatically shrinks several pixels every second or so as long as the search bar is opened. When it reaches to 0, it just starts shrinking from full again.

Disabling FindBar-Tweak solves the problem.

FF: 45.0a1 (2015-11-24)
FBT: 2.1.3

Screenshot: http://i.imgur.com/x9qBHWe.png

**Comment by Quicksaver** [comment]
Does that happen when you disable all other add-ons except for FBT? Also, what Firefox version are you using, and are you using the latest FBT version 2.1.3?

**Comment by Quicksaver** [comment]
Same thing as in your other issue? Firefox 45?

**Comment by Nidre** [comment]
Will try in a sec.

**Comment by Nidre** [comment]
Yeap. It still happens all addons disabled except for FBT.

**Comment by Quicksaver** [comment]
If you're in Nightly then beta version 2.1.4b1 should fix it: https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.4b1

**Comment by Nidre** [comment]
@Quicksaver  Would that break the update cycle? Or would automatically grab the next available update from AMO?

**Comment by Nidre** [comment]
I can confirm it solved btw.

**Comment by Quicksaver** [comment]
It'll still grab 2.1.4 automatically when I upload it to AMO. 2.1.4 > 2.1.4b1. :)
