### ISSUE TITLE
Preferences Window is Empty

### ISSUE THREAD

**Issue by Nidre** [Quicksaver/FindBar-Tweak#234]
Well, title says it all Preferences window is empty.

FF: 45.0a1 (2015-11-24)
FBT: 2.1.3

http://i.imgur.com/4zLLYw4.png

**Comment by Quicksaver** [comment]
Yeah there are some initialization issues in the latest Nigthly build. I've already fixed it, just haven't pushed a new version to AMO yet.

**Comment by Quicksaver** [comment]
Ditto for #233 ;)

**Comment by Nidre** [comment]
https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.4b1 solved it as you've mentioned.
