### ISSUE TITLE
Disable the Ctrl-a keyboard shortcut on Mac OS X

### ISSUE THREAD

**Issue by machsna** [Quicksaver/FindBar-Tweak#236]
It appears that on Mac OS X, the Ctrl-a keyboard shortcut toggles the *Highlight All* button when the (normal) Findbar is opened. This interferes with the normal behaviour of Ctrl-a on Mac OS X. On Mac OS X, Ctrl-a is supposed to move the insertion point to the beginning of the current line (emacs style).

An opened Findbar hijacks the Ctrl-a keyboard shortcut. Ctrl-a no longer moves the insertion point to the beginning of the current line. Instead, it only toggles the *Highlight All* button. Only when the Findbar is closed, Ctrl-a defaults back to its normal behaviour.

The interference with the normal behaviour of Ctrl-a is quite annoying to people like me who have internalized Ctrl-a and regularly use it in text input windows, in the Adress bar, in the Findbar search field, etc. etc. When I want to use Ctrl-a in the normal way, I have to close the Findbar first, and in the Findbar search field, it cannot work ever. Of course, the annoyance is relatively small when compared to the overall benefits of the *FindBar Tweak* extension, but still.

I would suggest a preference for disabling the *FindBar Tweak*’s Ctrl-a keyboard shortcut.

Similar issues might potentially occur on other OS, though that seems less likely. On Linux, the keyboard shortcut for toggling the *Highlight All* button is apparently not Ctrl-a (which would interfere with the usual Ctrl-a shortcut for *select all*), but Alt-a. I cannot tell whether this could also interfere with some other keyboard shortcut.

**Comment by Quicksaver** [comment]
FBT doesn't really implement any such shortcut (I didn't even know it existed, Ctrl+A in windows selects text, that's it, but I guess that depends on your OS localization). Does it also do that if you disable the add-on in the normal findbar?

**Comment by machsna** [comment]
Oh-oh, my bad. I assumed that feature came with FBT … because I assumed all the fancy stuff came from FBT … proceeding to Bugzilla, then.

**Comment by Quicksaver** [comment]
I'm still curious because, unless I'm mistaken somehow, I don't believe the native findbar (in other words, Firefox itself) is doing that either. Have you tried disabling all your add-ons and see if Ctrl+A still toggles Highlight All?

I know that in Windows, Alt+A toggles it because the letter "A" is the defined access key for that button (I don't know why it isn't H though, you'd have to ask them at Mozilla). But in other localizations, that key likely changes, for instance if the defined key was "T" (as I believe it is for the portuguese localization), then Alt+A won't work that way anymore and you'd have to press Alt+T to toggle that button instead.

Since Macs don't have the alt key usually, I wonder if they changed it to the ctrl key instead? Although I would have thought it would be the option key in that case.

**Comment by Quicksaver** [comment]
(Note that by "access key" I mean the letter that is underlined in the button text "Highlight All". It's the same thing for other buttons and menus and stuff.)

**Comment by machsna** [comment]
It turns out other people had complained about this issue before me:

https://bugzilla.mozilla.org/show_bug.cgi?id=672607

I have found a workaround: Disable the *Highlight All* button by modifying userChrome.css accordingly. Of course, this utterly disables the button. Fortunately, I don’t need the button because I have FBT. ☺ I have described the details at the above Bugzilla bug.

The fact that hiding the button removes the keyboard shortcut kinda supports your access key theory. However, the access key keyboard shortcut on OS X Firefox take Ctrl+Option, not just Ctrl. I vaguely remember it used to be just Ctrl, but they changed it. I have no idea whether there is a special exception for UI access keys.

BTW, the option key on a mac cannot be used as the single modifier key of a keyboard shortcut. It does not work like an Alt or Meta key, but like an AltGr key or third-level chooser. And the Ctrl key is not really being used except for simulating a right-click and for Emacs-like text commands.

Please accept again my apologies for posting this inaccurate bug report. At least it had a positive outcome: I am glad the issue is solved for me now (I am still thrilled that Ctrl-a now works even in the Findbar search field).

**Comment by Quicksaver** [comment]
> BTW, the option key on a mac cannot be used as the single modifier key of a keyboard shortcut. It does not work like an Alt or Meta key, but like an AltGr key or third-level chooser. And the Ctrl key is not really being used except for simulating a right-click and for Emacs-like text commands.

Thanks for the explanation! I didn't know this, it does change my view of keyboard shortcuts there.

> Please accept again my apologies for posting this inaccurate bug report.

You have nothing to apologize for. It was a valid bug report in the sense that something wasn't working as you expected. And we all learned from it. So thank you for filing it and following through as you have so far. :)

**Comment by machsna** [comment]
> Thanks for the explanation! I didn't know this, it does change my view of keyboard shortcuts there.

Thinks are still a little more complicated than that, since a few apps such as the Terminal.app or X11.app can be set to use the Option key as a Meta key, for doing Linux-like stuff. And except for the Emacs-like text commands, the Ctrl key is of course free to be used as a modifier key like the Cmd key. It is used very seldom in native apps, but using Cmd+Ctrl combos is a great way of defining your own keyboard combos that are very unlikely to interfere with any existing combos. And the Option key is of course used very often in combination with the Cmd key – just as the Shift key is. And in the same way as a Cmd+Shift+a combo can be thought of as a Cmd+A combo (since Shift+a really is *A*), a Cmd+Option+a combo can be thought of as a Cmd+å combo (since Option+a really is *å*).
