### ISSUE TITLE
F3 to always repeat last search term

### ISSUE THREAD

**Issue by DavidGP** [Quicksaver/FindBar-Tweak#237]
Did I miss some setting, or why is it that I can't simply repeat the last search term after changing to another web page or to another tab?

I'd need this feature about a 100 times a day, but it never works, instead I ALWAYS have to type the SAME search term over and over :(

**Comment by Quicksaver** [comment]
That should be happening of course. Have you tried disabling all your other add-ons and see if it still behaves like that? If it does, can you give me some exact steps to reproduce please?

**Comment by Quicksaver** [comment]
Please re-open if this is still happening and you can provide any more info.
