### ISSUE TITLE
Quick Find shortcuts not work

### ISSUE THREAD

**Issue by gwarser** [Quicksaver/FindBar-Tweak#238]
`/` and `'` have no effect on Firefox 46, Linux Mint when FindBar-Tweak is enabled.

**Comment by Quicksaver** [comment]
Already fixed locally, the next update should work properly. I will upload at at the end of the week. Please reopen if by next week when it updates they still don't work.

**Comment by gwarser** [comment]
Works fine in v2.1.6b2. Thank you.
