### ISSUE TITLE
Sights/highlights grid/other stuff stopped working

### ISSUE THREAD

**Issue by guitarjorge24** [Quicksaver/FindBar-Tweak#239]
After I updated the add on today, the sights are now showing up anymore even though they're enabled on the settings. I have version 2.1.7 but I'm not sure if the issue started with 2.1.6 or 2.1.7

**Comment by Quicksaver** [comment]
Have you restarted Firefox? Sometimes the add-on fails to initialize properly after an update (although that's rare and I'm still trying to figure that one out).

**Comment by guitarjorge24** [comment]
I've tried restarting Firefox twice but it didn't work. I also tried disabling FT Deep Dark theme which had just updated as well but it didn't work either.

**Comment by ArkadiuszMichalski** [comment]
Same here, I'm back to 2.1.5 and all works.

**Comment by Quicksaver** [comment]
Of all the things I could have screwed up, it was the script that controls the colors of everything. It's not that sights and the grid wasn't working, it's that it had no color, so you couldn't see it... Fixed version coming soon.
