### ISSUE TITLE
Some options stopped working

### ISSUE THREAD

**Issue by justanotheranonymoususer** [Quicksaver/FindBar-Tweak#242]
Hi, 

The following options stopped working for me. I think that it has to do with the update to Firefox 44.
* Show highlights grid in the scrollbar.
* Show sights on the current search hit.

Maybe something else stopped working, but that's what I noticed.

Can you reproduce it with Firefox 44? If not, I'll try to check whether I have a conflicting add-on.
Thanks.

**Comment by Quicksaver** [comment]
Have you updated FBT to the latest version 2.1.8? It's supposed to fix this.

**Comment by justanotheranonymoususer** [comment]
Yes, that fixed it, thanks.
