### ISSUE TITLE
Firefox 44 breaks+ themes Beyond australis

### ISSUE THREAD

**Issue by MacgyverJohnson** [Quicksaver/FindBar-Tweak#246]
As u know might know from firefox 44+ complete themes are broken…a light grey over lay is present in the personal toolbar..which can be work around by the following code in userChrome.css situated in profile/chrome folder

`@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
#navigator-toolbox > toolbar:not(#toolbar-menubar):not(#TabsToolbar) {
background-image: none;
}
#nav-bar {
background-image: linear-gradient(rgba(253, 253, 253, 0.42), transparent) !important;
}
#PersonalToolbar{
background: transparent !important;
background-color: hsla(253,253,253,0.42) !important;
}`
my problem is when slim chrome is enabled and hide nav bar is enabled in beyond autralis this doesn't work..could please add a few lines so that it could work with silm chrome…thanks
Author of the code Nemexixx https://www.reddit.com/user/Nemexixx
https://www.reddit.com/r/firefox/comments/42v11w/firefox_44_breaks_complete_themes/czdwmob
 

Sent from Windows Mail

**Comment by MacgyverJohnson** [comment]
Without slim chrome
![screenshot 94](https://cloud.githubusercontent.com/assets/17729946/13612946/29b20086-e594-11e5-8e6e-dd71254ebff1.png)
with slimchrome
![screenshot 93](https://cloud.githubusercontent.com/assets/17729946/13612947/29b49e2c-e594-11e5-9e4e-d2f1fd4cd4fe.png)

**Comment by Quicksaver** [comment]
I replied to your e-mail. You posted this in the wrong support page BTW.
