### ISSUE TITLE
Feature: Option to disable current search hit until F3 is pressed

### ISSUE THREAD

**Issue by DerpMcDerp** [Quicksaver/FindBar-Tweak#248]
The way Findbar Tweak with "highlight all" currently works like this:

1. When you push ctrl+F, the findbar opens and the edit box is focused.
2. You type "foo". All instances of "foo" are highlighted in the highlights color. Any selected text in the page is cleared. The current search hit of "foo" is selected and set to the current hit color and scrolls into view.

There should be a way to make Findbar Tweak work more like this:

1. When you push ctrl+F, the findbar opens and the edit box is focused.
2. You type "foo". All instances of "foo" are highlighted in the highlights color. The current search hit is NOT set and the page is NOT scrolled. Any text selections on the page remain selected.
3. You push F3. Any selected on the page is cleared. The current search hit of "foo" is selected and set to the current hit color and scrolls into view (the current search hit set is the one that would have been set in step 2 above).

Something like a "Don't set current search hit until 'Find Again' (F3)" option would work.

**Comment by Quicksaver** [comment]
What's the gain in keeping the previous text selection?

**Comment by DerpMcDerp** [comment]
I'm not committed to it. It's just kind of strange having it wiped out at that point.

**Comment by Quicksaver** [comment]
Without a reason to do it, I'm afraid I can't really implement something like this. I only see negative drawbacks from it: harder to copy the found match, can't follow through to links by hitting enter when searching for links, if when you find there are no matches visible but there are matches on the page, you wouldn't know it easily...

**Comment by DerpMcDerp** [comment]
There are 2 big reasons to implement this:

1. Lets say you're in the middle of the page and type a word. Maybe you made a typo or maybe you typed something that appears above the section of the page where you're currently looking. Now the page gets scrolled near the top and you lose what you were looking at.

2. Lets say you have some text selected on the page and want to start searching from where the selection is on. You push ctrl+f and now type a word. Lets say you make a typo and the search overshoots. Now you push backspace, the position of the search gets reset to the new position instead of resuming from the previous origin.

> harder to copy the found match

If you're doing a non-regexp search, just push ctrl+a then ctrl+c to copy the text in the find bar's edit box. If you're doing a regexp search then push F3 then ctrl+c.

> can't follow through to links by hitting enter when searching for links

Push F3 then enter.

> if when you find there are no matches visible but there are matches on the page, you wouldn't know it easily

But sometimes you just want to see if there are certain words that match on the current screen instead doing a full blown page search. So having it scroll to matches on the page is counter productive.

If the highlight scrollbar feature is enabled, you tell by looking at the scrollbar where the highlights are. It also has the advantage of not initially scrolling into view so you can see if the matches are above or below the section of the window you're looking at.

If the highlight scrollbar feature is disabled, you can look at the number of matches in the findbar and/or look at the background color of the findbar's edit box.

**Comment by Quicksaver** [comment]
I think this is turning into a discussion about something very different from your original request. It seems that what you want is not have the page to scroll to the current match. The implications of (not) scrolling are very different from the implications of (not) selecting the match. And that is more easily done. ;)

**Comment by Quicksaver** [comment]
Although now that I think about it, not scrolling wouldn't stop the problem with it finding from the position of the current match, so it would still need to not actually select the match as well. Well I do see how it can be useful, so I'll still look into it of course.
