### ISSUE TITLE
Findbar to stay open on all webpages always

### ISSUE THREAD

**Issue by gotquestions** [Quicksaver/FindBar-Tweak#250]
Findbar is closed at each new tab opening.
How can I keep it open continuously after firefox restart and on every webpage continuously, which is how it use to always be?
Thanks.
Findbar Tweak 2.1.9
Firefox 44

**Comment by Quicksaver** [comment]
FBT's preferences - General pane - "Use a single global findbar for all tabs". It's the very first preference in there. ;)
