### ISSUE TITLE
ZeroHello be invisible when "Highlight All" with the extension

### ISSUE THREAD

**Issue by yfdyh000** [Quicksaver/FindBar-Tweak#255]
ZeroHello of ZeroNet. https://github.com/HelloZeroNet/ZeroHello.
testcase: https://dl.dropboxusercontent.com/u/72126631/ZeroHello%20testcase.zip

STR: Type the "hours" to findbar. works fine without the extension.
Actual results: I see some "findbartweak" elements is inserted into the document, and the body be styled the "position: relative;", the content will be visible if removed the style.

**Comment by Quicksaver** [comment]
Of all the ways I expected that code to possibly break websites, I would have never imagined setting ```position:relative;```on the body element be one...

**Comment by Quicksaver** [comment]
Can you confirm that [beta version 2.1.10b1](https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.10b1) works fine (and that it doesn't break other websites)?

**Comment by yfdyh000** [comment]
Looks good.
