### ISSUE TITLE
Add functionality to notify user when wraparound occurs

### ISSUE THREAD

**Issue by Gitoffthelawn** [Quicksaver/FindBar-Tweak#256]
Can you add some sort of obvious notification when find wraparound occurs?

Perhaps a sound, a brief overlay message, or even a message box like https://addons.mozilla.org/firefox/addon/new-find-toolbar-with-alert/

**Comment by Quicksaver** [comment]
#61.

**Comment by Gitoffthelawn** [comment]
Thanks.  I didn't read that far back... that was 3 years ago! :-)
