### ISSUE TITLE
Color of current item seems to be broken

### ISSUE THREAD

**Issue by Gitoffthelawn** [Quicksaver/FindBar-Tweak#257]
Tested with a fresh install of Firefox v46.0.1 with FBT v2.1.9 (no other extensions).

Steps to reproduce:
1. Start Firefox
2. Press Ctrl+F to open the find bar.  It should be empty.
3. Perform a *find* operation for any text that has multiple occurrences on a page

What happens:
The first match is instantly highlighted the correct "current match" color.  After about a second, all the other matches are highlighted the correct "secondary match" color.  The issue is that at the same time the other matches are highlighted, the first match changes color to a third color that is not specified anywhere in the preferences.

Quirks:
The issue happens most of the time, but on same pages does not happen.  If there is trouble reproducing this issue, please try another website.

**Comment by Quicksaver** [comment]
Do you mean it goes back to the normal text selection color?

**Comment by Gitoffthelawn** [comment]
*Do you mean it goes back to the normal text selection color?*

Yes

**Comment by Gitoffthelawn** [comment]
Is this a bug or am I not understanding the functionality?

**Comment by Quicksaver** [comment]
It's a bug. ;) Any matches it shows you are their own special category of text selections, the same kind that happens when you select text with your mouse for instance, except of course for different colors and such things.

The "current match" is actually a "normal text selection", except it has a different color. There's something going on that's reverting that special status, so it turns back to a normal text seleciton.

**Comment by Gitoffthelawn** [comment]
I'm glad I didn't do all that diagnosis work for naught!

**Comment by Quicksaver** [comment]
In [beta version 2.1.10b1](https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.10b1), the current match should still blink for a moment sometimes, there's no real way to avoid it if it does, but it should keep the correct color afterwards.

**Comment by Gitoffthelawn** [comment]
That was quick!  Thanks!  Hopefully the blink won't be distracting... especially on slower devices.

What's your ETA for a push to AMO?

**Comment by Quicksaver** [comment]
Still this month hopefully.

**Comment by Gitoffthelawn** [comment]
Great! Thanks!
