### ISSUE TITLE
New Find behavior in Nightly.

### ISSUE THREAD

**Issue by streetwolf** [Quicksaver/FindBar-Tweak#259]
Hi Luis:

You might want to take a look at this new feature that is now on Nightly.  At the moment it only seems to permanently turn highlighting on even though the FBT option is off.  Also the patch added a dimming effect when searching and possibly some other stuff.

https://bugzilla.mozilla.org/show_bug.cgi?id=384458

**Comment by Quicksaver** [comment]
Already replied to your e-mail. ;)

**Comment by Quicksaver** [comment]
Actually I'll use #177 to track this.
