### ISSUE TITLE
German translation mistake in about:findbartweak#tweaks

### ISSUE THREAD

**Issue by gerib** [Quicksaver/FindBar-Tweak#261]
"bis zum nächsten Satzzeiten" should be "bis zum nächsten Satzzeichen".

**Comment by mausalimi** [comment]
there's another typo in options.dtd

ohne weiterer Zeichen einzugeben

should be

ohne weitere Zeichen einzugeben

very minor prob, but i stumbled upon it right now...

**Comment by Quicksaver** [comment]
You can always register on Babelzilla and make the corrections there yourselves. See the [localization notes here](https://github.com/Quicksaver/FindBar-Tweak#localization). :)
