### ISSUE TITLE
[firefox nightly] search doesn't work on some pages since ~2016-06-11

### ISSUE THREAD

**Issue by avih** [Quicksaver/FindBar-Tweak#263]
Using Firefox nightly 2016-06-17 on OS X 10.11.5, trying to invoke using command-f .

On some github pages it works correctly (e.g. https://github.com/Quicksaver/FindBar-Tweak/issues ) while on other pages the search box doesn't show (and doesn't work if I assume it's just invisible), e.g. at https://github.com/ccxvii/mujs/commits/master

At the general options I have:
- Close the findbar when it loses focus.
- Search for text when I start typing.
- Always use normal Findbar.

I played a bit with the options without noticing a change, but didn't try restarting the browser between changes.

This issue could be related to this or to a derivative of it: https://bugzilla.mozilla.org/show_bug.cgi?id=384458

**Comment by blackwind** [comment]
I'm experiencing the same issue and getting the same traceback as @bsiegel in #266. I'd estimate it occurs on maybe a third of all pages I visit, with the rest working just fine. Alas, I can't find any method to the madness (other than it appears to only affect e10s), nor can I reproduce in a fresh profile.

As little as you have to go on here, this should be a top priority, as it not only breaks the add-on, but core functionality as well.

**Comment by mzso** [comment]
Does the findbar gets focus when you open them for you guys?


[**@avih**](https://github.com/avih) commented on [2016. jún. 17. 21:46 CEST](https://github.com/Quicksaver/FindBar-Tweak/issues/263#issue-160961757 "2016-06-17T19:46:54Z - Replied by Github Reply Comments"):

> This issue could be related to this or to a derivative of it: [https://bugzilla.mozilla.org/show_bug.cgi?id=384458](https://bugzilla.mozilla.org/show_bug.cgi?id=384458)

Huh. I didn't notice that. The new highlighting actually looks pretty neat.

**Comment by Quicksaver** [comment]
Should also have been closed by 0d2bb56f7cad6c1b019dfaf3aa74dec90754e392.

**Comment by Quicksaver** [comment]
All issues should be fixed in [beta version 2.1.11b1](https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.11b1). Please give it a try and let me know if you still have any problems.

**Comment by Quicksaver** [comment]
Also, I'm sorry it took me so long to get to this.
