### ISSUE TITLE
Searching in PDF stopped working in FF48

### ISSUE THREAD

**Issue by DrZruda** [Quicksaver/FindBar-Tweak#265]
It works on regular websites, but when searching in the internal PDF viewer, no matches are displayed, although they do show up after clicking 'Find All'. Once FBT is disabled, the internal search works as expected.

**Comment by Quicksaver** [comment]
It's possible they changed something in Firefox 48 that I haven't added compatibility for yet, I definitely have to check this out.

**Comment by Erlotinib** [comment]
Hello,

I've got the same issue with FF48 and FF50 (dev edition).
When I open the search bar on a pdf I got the message (it repeats each time I press on an arrow to search for the next occurence) :

`TypeError: this.unWrap.FindStates is undefined           PDFJS.jsm:56:3`

which point to this part of the code : 
```
receiver: function(data) {
		if(!this.findController) { return; }

		// this is needed so objects created in a privileged scope (the message data) can be used in unpriviliged scope (webpage/pdf reader)
		var fakeEvent = Cu.cloneInto(data, content);

		// We can't pass fakeEvent below and let the native method handle it because of a lot of limitations with its binds and stuff,
		// especially because we also replace PDFJS.findController.nextMatch. So we have to reproduce the whole thing here.
		// This turns out to be good because we can also apply our delay settings here as well.

		if(this.findController.state === null || fakeEvent.type !== 'findagain') {
			this.findController.dirtyMatch = true;
		}
		this.findController.state = fakeEvent;
==>		this.findController.updateUIState(this.unWrap.FindStates.FIND_PENDING);

		Timers.cancel('PDFFindTimeout');

		this.findController.firstPagePromise.then(() => {
			this.findController.extractText();

			if(this.findController.state.type === 'find') {
				Timers.init('PDFFindTimeout', () => {
					this.findController.nextMatch(this.findController.state.type);
				}, this.findController.state.delay);
			} else {
				this.findController.nextMatch(this.findController.state.type);
			}
		});
	},


Thanks for your addon
regards

```

**Comment by EstelaParada** [comment]
I've got the same issue in FF49.

**Comment by LucidComplex** [comment]
On FF49, same issue. No feedback is received at all.

**Comment by gitterliu** [comment]
Firefox 49.02 too. The pdf reader's search bar doesn't search at all

**Comment by Quicksaver** [comment]
All issues should be fixed in [beta version 2.1.11b1](https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.11b1). Please give it a try and let me know if you still have any problems.

**Comment by Quicksaver** [comment]
Also, I'm sorry it took me so long to get to this.

**Comment by voxadam** [comment]
I can confirm that 2.1.11b1 works beautifully in nightly, _53.0a1 (2016-12-11) (64-bit)_.

Thanks for all you hard work on this excellent extension. Personally, I believe much of this extension's functionality should be integrated directly into Firefox.

**Comment by bnbaz** [comment]
Also works in Fx 50.0.2 x64 on Win10 using 2.1.11b1 :)
