### ISSUE TITLE
FF 48.0.1 on Mac

### ISSUE THREAD

**Issue by billfr** [Quicksaver/FindBar-Tweak#269]
FF 48.0.1 on Mac:      Command F finds first instance (match) and correctly reports total number of matches.  

BUT, FindBar-Tweak does not show them one by one as it used to.  i.e. no longer steps thru the matches when you click down arrow.

**Comment by Quicksaver** [comment]
This is probably the same as #263 and #265, but I'll leave this open to make sure when I work on it.

**Comment by billfr** [comment]
This problem has miraculously disappeared.  Sheesh.
