### ISSUE TITLE
FF 51 : Doesn't catch first char.

### ISSUE THREAD

**Issue by Betsy25** [Quicksaver/FindBar-Tweak#270]
Using Firefox 51 (32bit on Win7)

With the option "Search for text when I start typing", upon typing, FB doesn't catch the first typed char and only search from the 2nd typed char on.

**Comment by mzso** [comment]
I think this might be the old issue of the findbar not opening fast enough. Which can't be helped.
Does it still happen when you type really slowly, like one character per second?

**Comment by Betsy25** [comment]
Yes, typing slow doesn't solve anything, upon typing the first char the find dialog comes up empty and only fills from the seconds char on.

**Comment by mzso** [comment]
Then I think it's a variant of bug #268. I have to press twice the hotkey for the findbar to get focus. In your case, with "Search for text when I start typing" enabled this just means typing. And only the second character will give focus to the findbar.

**Comment by Quicksaver** [comment]
All issues should be fixed in [beta version 2.1.11b1](https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.11b1). Please give it a try and let me know if you still have any problems.

**Comment by Quicksaver** [comment]
Also, I'm sorry it took me so long to get to this.
