### ISSUE TITLE
Does not find matches until you have scrolled the text into view

### ISSUE THREAD

**Issue by deadlydog** [Quicksaver/FindBar-Tweak#271]
I love your extension, thank you for creating it. One problem I've found though is that often when searching for a string, it will not find any matches on the page until I scroll down and bring a match into view in the browser, and then do the find again. The work around is easy enough; I typically scroll down to the very bottom of the page and then do the search again. It seems to happen on certain websites/webpages more than others, so I think it may be related to how the webpage is written. Perhaps it is using some javascript to not load all of the information into the DOM until it's actually needed to be visible or something (although the scroll bar doesn't indicate that the page gets "longer" when scrolling down to the bottom). I know I've seen this problem on various different random sites. One that I know it happens consistently on is the Visual Studio Team Services -> Work tab -> Backlogs page.

Actually, checking out the Page Source I see this on that specific page:

```
 <div class="content-section">
    <script type="text/javascript">
        require(["Agile/Scripts/TFS.Agile.ProductBacklog", "Agile/Scripts/TFS.Agile.Controls", "Presentation/Scripts/TFS/TFS.UI.Controls"], function (TFS_AGILE_PRODUCTBACKLOG, TFS_AGILE_CONTROLS, TFS_UI_CONTROLS) {
            $(function () {
                var productBacklog = new TFS_AGILE_PRODUCTBACKLOG.ProductBacklog($(".main-content"), true /* deferInitialization */);

                // TODO: Ensure droppable info (aka getSprintViewOptions) is provided to treeviews
            });
        });
    </script>
```

So it looks like it may be a javascript control.  Because of that, I'm not sure if there's anything you can do in your tool or not, but thought I'd mention it in case you have any ideas. This TFS page is one site I've noticed the problem on, but I've noticed it on other websites too. The next time it happens I'll try and remember to come back here and post more examples of other sites with the problem so you can look at how they are being done.

**Comment by Quicksaver** [comment]
First of all, I'm sorry it took me so long to respond.

It's true that if the content is generated depending on some user action, like scrolling, there's really nothing that can be done. Those parts of the page simply don't exist to be searched. If you want, please give me a specific link of when this happens (I can't find that page) if you think that's not the case though.
