### ISSUE TITLE
Prevent gmail (and other trashy websites) from swallowing hotkey

### ISSUE THREAD

**Issue by mzso** [Quicksaver/FindBar-Tweak#275]
It's not strictly a FBT issue, but hell freezes over before gmail will deal with it. 
The issue is that only the ctrl+f hotkey works when I'm on gmail, even though I have hotkeys disabled in gmail. I always prefer the quick findbar hotkeys. (I have custom ones with keyconfig, but defaults don't work either.)

**Comment by Quicksaver** [comment]
I'll take a look, but it might not be easy. As a general rule, I prefer to avoid messing with websites keyboard handlers and let them do their thing. But I'll see if there's anything I can do.

**Comment by Quicksaver** [comment]
Unfortunately this simply won't happen. It's not for the add-on to override keys handlers in websites. It's not something that's so easily done either. As I mentioned, I'd rather not mess with how websites themselves work, it does annoy me at times as well (Github here for instance has some special keys as well which trigger some actions when I actually want to search). But that's how the website intends to behave, and even if you can disable those hotkeys in gmail, there's no telling it's not still trying to do something with them.
