### ISSUE TITLE
"Remove highlights when the Findbar is closed" doesn't work in Firefox 50 beta

### ISSUE THREAD

**Issue by justanotheranonymoususer** [Quicksaver/FindBar-Tweak#276]

**Comment by SomeDude77** [comment]
Yup, same issue. And "list all matches in the sidebar" doesn't work either.

**Comment by Quicksaver** [comment]
All issues should be fixed in [beta version 2.1.11b1](https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.11b1). Please give it a try and let me know if you still have any problems.

**Comment by Quicksaver** [comment]
Also, I'm sorry it took me so long to get to this.

**Comment by SomeDude77** [comment]
Thanks, works like a charm.
