### ISSUE TITLE
Findbar and input don't get focus after Ctrl+F, since Fx51b1

### ISSUE THREAD

**Issue by yfdyh000** [Quicksaver/FindBar-Tweak#278]
Regression window:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=ecd7d4abe30d917fac834700bf6910cdaf7a3010&tochange=0ec1ef34854780ad5f6ca39cfb33b190356119f0
0ec1ef348547	Mike de Boer — Bug 1280876 - don't take screenshots of pages that have the findbar open. r=jaws,mconley

**Comment by Quicksaver** [comment]
Yep, #268.
