### ISSUE TITLE
"Highlight all matches by default" not working

### ISSUE THREAD

**Issue by tonglil** [Quicksaver/FindBar-Tweak#279]
When I turn on this option, the "Highlight All" option when I cmd+f is not enabled, and even if I enable it manually, when I cmd+f, it resets to disabled.

FF 50.0

**Comment by mzso** [comment]
Hi!
You can try: https://github.com/Quicksaver/FindBar-Tweak/issues/268#issuecomment-249835845
But you may need FF53+ for it to work.

**Comment by tonglil** [comment]
I solved this for now by going into `about:config` and changing: `findbar.highlightAll;true`.

**Comment by Quicksaver** [comment]
Same as #274.
