### ISSUE TITLE
Findbar doesn't stay closed - FF 50

### ISSUE THREAD

**Issue by Bieeanda** [Quicksaver/FindBar-Tweak#280]
Pressing CTRL+F or the 'x' button on the bar closes it... temporarily. When I move to a different tab, the same bar is open with the same search string, and when I go back to the previous tab, the bar has opened itself again.

This just started happening after I upgraded to 50, and whatever is causing it seems to be stored in session data as well.

**Comment by mikhoul** [comment]
@Quicksaver  @Bieeanda   Same Bug here with FF 50 under Win7/64

After I restarted it was fine for 15/30 minutes but after FindBar was "sticky" again.

Here's a screencast to show the "bug" :  http://screencast-o-matic.com/watch/cDXq1GQec0

Regards :octocat:

**Comment by Quicksaver** [comment]
All issues should be fixed in [beta version 2.1.11b1](https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.11b1). Please give it a try and let me know if you still have any problems.

**Comment by mikhoul** [comment]
Fixed for me !    :smile: 

Thanks :+1:
