### ISSUE TITLE
Bug with Firefox 50.0 :   The Findbar toolbutton stay "stuck" in open mode aftr using it.

### ISSUE THREAD

**Issue by mikhoul** [Quicksaver/FindBar-Tweak#281]
Bug with Firefox 50.0 under Win7/64 : 

The Findbar toolbutton stay "stuck" in  open mode after using it once.  

It's annoying it open Findbar at each newtab I open, the only way to reset it I've found is to restart Firefox. :disappointed: 

Here's a screencast to show the "bug" : http://screencast-o-matic.com/watch/cDXq1GQec0

If you need any more information just ask me !

Best Regards :octocat:

**Comment by Quicksaver** [comment]
I don't see this anymore, so I'm going ahead and say this is #280.
