### ISSUE TITLE
Highlight all etc

### ISSUE THREAD

**Issue by merula123** [Quicksaver/FindBar-Tweak#283]
1. "Highlight all" does not work anymore

2. Items are not shown in the scrollbar anymore (before they were and in colour, too) 

Maybe more problems (because of a FF update ?), I just noticed these 2 things since today

**Comment by LafinJack** [comment]
This happened to me after FF 50. While highlight all still works for me, I have to reenable it every time I enable the find bar, even though I have default highlight all enabled in the options.

**Comment by HYBRID-BEING** [comment]
Duplicate of issue #279

**Comment by Quicksaver** [comment]
Actually a duplicate of #263. Well... they both pretty much have the same cause.
