### ISSUE TITLE
Theme issue

### ISSUE THREAD

**Issue by letrollpoilu** [Quicksaver/FindBar-Tweak#284]
I'm using the FT DeepDark theme, and when I put the search bar in the top of firefox, the search bar is not black but kind of grey.

![untitled](https://cloud.githubusercontent.com/assets/7238442/21079943/421aee74-bfa2-11e6-894e-912f669eeda2.png)

**Comment by Quicksaver** [comment]
Yep, I was looking into it after seeing your review. Turns out I wasn't seeing it because I was using another add-on of mine (Beyond Australis) which kinda fixes it. I will be sure to fix it for the next update.

Thank you for moving the discussion about your issues here by the way. :)

**Comment by letrollpoilu** [comment]
Thanks a lot :)

Yeah sorry, I don't know why I wrote in the review, I guess I wasn't fully woke up like a Sunday morning ^^

Good luck with it and thanks a lot!

**Comment by Quicksaver** [comment]
[Beta version 2.1.11b3](https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.11b3) should fix this. Please give it a try and let me know how it looks for you.

**Comment by letrollpoilu** [comment]
This works perfectly! Thanks a lot you are doing a great job there!

![untitled](https://cloud.githubusercontent.com/assets/7238442/21080502/0f0a0fd8-bfb1-11e6-8768-e1c8b51f3148.png)
