### ISSUE TITLE
How do we turn off FindBar-TWeak notifications?

### ISSUE THREAD

**Issue by c627627** [Quicksaver/FindBar-Tweak#286]
I copy-paste my Firefox profile all the time.
SO even if the Find-Bar Tweak notification in the right lower corner appears only once - it appears all the time for me because I copy-paste my Firefox profile all the time to reset it.
How do we turn OFF pop-ups informing us about new FindBar-Tweak features?

**Comment by Quicksaver** [comment]
Those notifications only appear when updating the add-on. So for instance if you copy your profile onto a new (empty) profile, or if you copy it onto an existing profile with the same existing version of the add-on, you will not see these notifications. The absolutely only case where you can see this notification when copying your profile across folders, is if you copy a more recent version of the add-on over an older version of the add-on.

Either way, if you still want to disable it, the option to do it is in the About page of the add-on's preferences.
