### ISSUE TITLE
Misc problems

### ISSUE THREAD

**Issue by kpanos777** [Quicksaver/FindBar-Tweak#287]
Win 7 (64-bit) , Firefox 51.0b1 (64-bit), FindBar Tweak previous Version 2.1.10 had only the Focus problem (could be bypassed by hitting Ctrl+F twice). Current version 2.1.11 has more bugs for me. Focus is fixed now but hitting Enter or F3 or Next/Prev buttons do nothing. Find results are highlighted only if I check the "Highlight All" button. Number of results is never displayed.

**Comment by Quicksaver** [comment]
Ah, I only saw this now, you did open the issue here. :)

As I mentioned in the review response, does this still happen if you disable all your other add-ons?

**Comment by Quicksaver** [comment]
And to confirm, the "Highlight all by default" and "Show matches counter in the findbar" options are still enabled, correct?

**Comment by kpanos777** [comment]
This behavior started as soon as I updated the addon from v10 to v11. No options were changed and yes these options were/are enabled.

Well. I disabled all addons but Findbar Tweak and still does not work. I also reset the addon prefs with no luck. In FF 51.0b1, if I disable the Findbar Tweak 2.1.11, then the Findbar works OK again. As I see, the only function missing then, is the "Sights" one. 

I tried the Tweak 2.1.11 in Firefox Nightly 53.0a1 (64-bit) and it works OK. Maybe it is a bug, but the "Highlight all" checkbutton is always checked. 

So, I believe it should be a version specific problem regarding FF 51.0b1. I will try to update FF to any newer version, if available (I use portable version)

**Comment by kpanos777** [comment]
Good news. I just updated to FF 51.0b7 (beta 64-bit) and your addon works OK again. So, it was probably a very version specific issue of FF and not the addon.

**Comment by Quicksaver** [comment]
That's very likely, yes. I have to admit that I did not notice you were not using the latest beta version of Firefox, otherwise I'd have suggested you try to update it first. I'm sorry about not noticing it sooner. The add-on makes a few assumptions based on your Firefox major version (50, 51, etc), that may have not yet been true in 51.0b1. Please let me know if any of the issues return.

**Comment by Quicksaver** [comment]
By the way, is there any chance I could ask you to update the review as well about this, since everything is working as expected now? :)
