### ISSUE TITLE
broken: "Double-clicking on a word also selects the following space"

### ISSUE THREAD

**Issue by msjasinski** [Quicksaver/FindBar-Tweak#289]
about:findbartweak#tweaks >>  Double-clicking on a word also selects the following space

I like this option un-ticked, but my preference gets lost, e.g. when I purge Firefox history.

**Comment by Quicksaver** [comment]
That is a native Firefox preference, if there is a problem with it that's a problem with Firefox, not with the add-on. At most, you may be losing the saved value of that preference or the intermediate one belonging to the add-on somehow. Deleting history should have nothing to do with it though, unless you're using something else other than Firefox's built-in clear history dialog. You have to try and find out exactly what application or action is cleaning up or resetting your profile (and thus your saved preferences), that is what is most likely causing the problem.
