### ISSUE TITLE
Findbar became page-wide?

### ISSUE THREAD

**Issue by SpellingSword** [Quicksaver/FindBar-Tweak#295]
I'm sure this is something stupid on my part but the findbar somehow became page-wide and I can't find an option that would shrink it back to the top-left corner. Help please?

**Comment by mikhoul** [comment]
Look here: http://i.imgur.com/83qX8z3.png

**Comment by SpellingSword** [comment]
I have. The first one just moves it down; the second one only moves the buttons to the left... Nothing to shrink it back.

This is what it looks like : 
![findbar](https://cloud.githubusercontent.com/assets/27512508/25056966/003674bc-2175-11e7-9c0c-0a63fb6c7234.PNG)

**Comment by mikhoul** [comment]
Hummm Strange...

Could you try to delete the addon AND the related entry in the `about:config` window, after reinstall the addon.

Something with the internal CSS seem "messed".

Regards :octocat:

**Comment by Quicksaver** [comment]
From the [add-on's description](https://addons.mozilla.org/firefox/addon/findbar-tweak/) (also see the 6th/last screenshot in there):
> - Resize the find text field by dragging its border (right border when the Findbar is on the left, left border when the Findbar is on the right)
-- Double-click on the border to immediately resize to the maximum/minimum width possible.

**Comment by SpellingSword** [comment]
Duh, Thanks!
