### ISSUE TITLE
Enhancement: make Options dialog non-modal.with an Apply button

### ISSUE THREAD

**Issue by IMeanReallyNow** [Quicksaver/FindBar-Tweak#72]
Would be great if the Options dialog box could be made non-modal.

It so frustrating trying to have the dialog open and trying to get back to the browser, and have it flash at me and having to close it before I can do anything. (Those flashes always seem to take forever!)

Making a non-modal dialog even better would be if it had an Apply button. 

With non-modality and an Apply button, making and testing and fine-tuning the options would be SO much more convenient. And having so many cool and subtle options almost demands an easier dialog box. 

Thanks for considering this.

**Comment by Quicksaver** [comment]
Options were completely redone for the next version, they behave as if instantApply was enabled, regardless of the setting. So this is no longer relevant.
