### ISSUE TITLE
New Feature: A minimize/restore sizing button

### ISSUE THREAD

**Issue by IMeanReallyNow** [Quicksaver/FindBar-Tweak#77]
It would be really good if there was a button on the bar that toggled between two different heights for the bar: 1) a "minimized" height where FBT had the same height as the native find bar, and 2) the last manually "expanded" height. 

Here's why: I use type ahead find all the time but I don't always need or want so see every instance in the page in context (FBT's right pane) and so I don't need to have FBT expanded. 

At those times, an expanded FBT can take up a significant -- and distracting --  portion of the window. But if it was the size of the native, it would be pretty out of the way, more like a common status bar. 

Currently there are only 2 options: 1) refocus and close, which at minimum requires 2 keyboard commands; or a mouse click, or 2) grab the upper edge and drag to resize. Neither is difficult, but both are a pain, especially 2, since you'll inevitably need to reverse the action the next time you want to see results in context, which for me is more or less half the time. So I'm frequently juggling the size of the panel. 

So I would want to have the ability to just a button it to minimize, and click the same button again to restore. 

More ideally  would be an option of 3 sizes -- minimum and user-set max, plus a user-set intermediate. That would cover most situations. But I imagine that would be more complicated. And, anticipating it, I can imagine that toggling through the 3 settings would lead to chasing the bar up and down to access the button, or buttons.... hmm.... 

A two way would be great though! :)

**Comment by Quicksaver** [comment]
The find all lists in the main browser window are gone now (version 2), so this is no longer relevant. I do plan to replace them with a more intuitive and easier-to-use sidebar panel, but I haven't gotten around to it yet.
