### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by bottleblue** [Quicksaver/FindBar-Tweak#78]
This a pretty nice addon. I wanted to suggest some things that might improve it.

The Highlight All, Match Case, Find in All Tabs, and x buttons are all the way on the right while the search box is all the way on the left. That's not a good place to put the buttons. Actually that's the worst place to put them. It should be next to the search box, after the matches counter. Or let us customize the order and where to put them, especially the close button. Some people might prefer the x button on the left, right, middle, after the search box, etc.

Let us close the find bar by double clicking it. This was my preferred method. .

An option to Find All in only the current tab. I know I could just ignore the rest of the tabs in the Find All box but it would look less cluttered if it only showed the search entries. 

This one might be a bug. When I open the Find bar it shows the last word I searched for. If I hit enter or click next it does not highlight all the words anymore. I have to manually type something in or click the Highlight All button twice to highlight the words again. 

How about some more Sights Styles? Maybe an arrow pointing next to the word? Or a rectangular box around the word?

**Comment by Quicksaver** [comment]
If this bug is still affecting you, please try the latest beta version 2b2 (https://addons.mozilla.org/firefox/addon/findbar-tweak/versions/) and see if it still happens there. If it does let me know.

**Comment by bottleblue** [comment]
I have not encountered this problem again thankfully. You think I should still download it?

**Comment by Quicksaver** [comment]
If the current version isn't giving you trouble you don't need to, it'll update automatically once I release it. ;)

**Comment by bottleblue** [comment]
Ok I'll just wait then. Thanks for keeping up on this. I'd totally forgotten about this problem. Nice to know your addon is still being updated :)
